// === Catálogo de productos EN CÓDIGO (Vercel-ready, sin base de datos) ===
// Patrón inspirado en scentualbliss: el catálogo cambia poco, así que vive en
// código. Esto hace que la tienda sea estática/ISR y funcione en Vercel sin DB.
// Lo dinámico (órdenes) va en Supabase.

export interface CatCategory {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  image: string;
}

export interface CatProduct {
  id: number;
  slug: string;
  name: string;
  categorySlug: string;
  reference: string;
  shortDesc: string;
  description: string;
  materials: string;
  dimensions: string;
  hardware: string;
  warranty: string;
  priceCop: number;
  compareAtCop?: number;
  stock: number;
  featured?: boolean;
  isNew?: boolean;
  image: string;
  /** Cantidad de fotos en /img/products: {slug}.webp, {slug}-2.webp, ... */
  photos?: number;
}

const MATERIALES =
  "Fabricados con madera y/o MDF, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.";

import { categoryStock } from "@/lib/stock";

const catImg = (slug: string) => categoryStock[slug] ?? `/img/categories/${slug}.webp`;
const prodImg = (name: string) => `/img/products/${name}.webp`;

export const categories: CatCategory[] = [
  { slug: "hogar", name: "Hogar", tagline: "Útiles y Decorativos", description: "Percheros decorativos con imágenes de paisajes y diferentes temáticas, útiles para colgar accesorios livianos, ofreciendo organización, funcionalidad y decoración en el hogar.", image: catImg("hogar") },
  { slug: "mascotas", name: "Mascotas", tagline: "Útiles y Familiares", description: "Percheros diseñados para los amantes de las mascotas: organiza correas, juguetes y accesorios de tu compañero con estilo.", image: catImg("mascotas") },
  { slug: "moteros", name: "Moteros", tagline: "Útiles y Seguros", description: "Percheros con temática motera para colgar cascos, chaquetas y accesorios de viaje. Vive la pasión por las carreteras.", image: catImg("moteros") },
  { slug: "bike", name: "Bike", tagline: "Útiles y Resilientes", description: "Percheros para ciclistas: organiza cascos, guantes y accesorios de tu bici con diseños llenos de aventura.", image: catImg("bike") },
  { slug: "guitarras", name: "Guitarras", tagline: "Útiles y Cómodos", description: "Percheros inspirados en la música, ideales para colgar accesorios y decorar el espacio de los amantes de la guitarra.", image: catImg("guitarras") },
  { slug: "personalizados", name: "Personalizados", tagline: "Útiles y Prácticos", description: "Percheros hechos a tu medida: nombres, fechas, logos o diseños únicos para regalar o decorar a tu estilo.", image: catImg("personalizados") },
  { slug: "corporativos", name: "Corporativos", tagline: "Útiles y Funcionales", description: "Percheros con la imagen de tu marca o empresa. Detalles corporativos útiles, funcionales y memorables.", image: catImg("corporativos") },
  { slug: "murales", name: "Murales", tagline: "Útiles y Decorativos", description: "Murales decorativos en madera que transforman cualquier pared en un espacio con personalidad y organización.", image: catImg("murales") },
  { slug: "souvenires", name: "Souvenires", tagline: "Útiles y Cómodos", description: "Recuerdos y detalles artesanales en madera, perfectos para sorprender en cualquier ocasión.", image: catImg("souvenires") },
  { slug: "dedios", name: "DeDios", tagline: "Útiles y Resilientes", description: "Percheros con mensajes e imágenes de fe y esperanza, para acompañar y decorar tu hogar.", image: catImg("dedios") },
  { slug: "variados", name: "Variados", tagline: "Útiles y Funcionales", description: "Diseños variados para todos los gustos: una selección versátil de percheros artesanales.", image: catImg("variados") },
];

// NOTA PRECIOS: los productos con referencia PH/PdD/CR/PG/PMS provienen de las
// fotos de la carpeta /productos; su precio es PROVISIONAL (por categoría)
// hasta que el inventario oficial los incluya. Medidas aproximadas.
const GARANTIA = "6 meses";

export const products: CatProduct[] = [
  // ===== HOGAR (fotos carpeta /productos/HOGAR) =====
  { id: 10, slug: "perchero-la-candelaria-bogota", name: "Perchero La Candelaria Bogotá", categorySlug: "hogar", reference: "PH1", shortDesc: "Calles coloniales de La Candelaria, Bogotá.", description: "Perchero decorativo con imagen de las calles coloniales de La Candelaria, en el centro histórico de Bogotá. Útil para colgar accesorios livianos y llenar tu hogar de identidad colombiana.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 35000, stock: 3, image: prodImg("perchero-la-candelaria-bogota"), photos: 3, materials: MATERIALES },
  { id: 11, slug: "perchero-la-candelaria-colores", name: "Perchero La Candelaria Casas de Colores", categorySlug: "hogar", reference: "PH1-1", shortDesc: "Fachadas coloridas del barrio La Candelaria.", description: "Perchero decorativo con las fachadas coloridas del barrio La Candelaria de Bogotá. Un toque alegre y muy colombiano para organizar tu entrada o habitación.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 35000, stock: 3, image: prodImg("perchero-la-candelaria-colores"), photos: 3, materials: MATERIALES },
  { id: 12, slug: "perchero-monserrate-bogota", name: "Perchero Monserrate Bogotá", categorySlug: "hogar", reference: "PH2", shortDesc: "El santuario de Monserrate sobre Bogotá.", description: "Perchero decorativo con vista panorámica del santuario de Monserrate y la ciudad de Bogotá. Útil, funcional y con el sabor de nuestra capital.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 35000, stock: 3, featured: true, image: prodImg("perchero-monserrate-bogota"), photos: 3, materials: MATERIALES },
  { id: 13, slug: "perchero-mandalas", name: "Perchero Mandalas", categorySlug: "hogar", reference: "PH3", shortDesc: "Mandalas multicolores llenos de energía.", description: "Perchero decorativo con mandalas multicolores, ideal para dar vida y energía a cualquier espacio mientras mantienes todo organizado.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 35000, stock: 3, image: prodImg("perchero-mandalas"), photos: 3, materials: MATERIALES },
  { id: 14, slug: "perchero-plaza-de-bolivar", name: "Perchero Plaza de Bolívar Bogotá", categorySlug: "hogar", reference: "PH4", shortDesc: "La Catedral y la Plaza de Bolívar de Bogotá.", description: "Perchero decorativo con la Plaza de Bolívar y la Catedral Primada de Bogotá. Historia y organización para tu hogar en una sola pieza.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 35000, stock: 3, featured: true, image: prodImg("perchero-plaza-de-bolivar"), photos: 3, materials: MATERIALES },
  { id: 15, slug: "perchero-muelle-luna", name: "Perchero Muelle a la Luz de la Luna", categorySlug: "hogar", reference: "PH5", shortDesc: "Muelle nocturno en tonos azules.", description: "Perchero decorativo con un muelle bajo la luz de la luna en tonos azules, con herraje central de búho. Serenidad y orden para tu espacio.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 3", warranty: GARANTIA, priceCop: 35000, stock: 3, featured: true, image: prodImg("perchero-muelle-luna"), photos: 3, materials: MATERIALES },
  { id: 16, slug: "perchero-ciclistas-atardecer", name: "Perchero Ciclistas al Atardecer", categorySlug: "hogar", reference: "PH6", shortDesc: "Siluetas de ciclistas al caer el sol.", description: "Perchero decorativo con siluetas de ciclistas al atardecer. Perfecto para los amantes de la bici y los paseos al aire libre.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 3", warranty: GARANTIA, priceCop: 35000, stock: 3, image: prodImg("perchero-ciclistas-atardecer"), photos: 3, materials: MATERIALES },
  { id: 17, slug: "perchero-bosque-otono", name: "Perchero Bosque de Otoño", categorySlug: "hogar", reference: "PH7", shortDesc: "Bosque otoñal en tonos dorados.", description: "Perchero decorativo con un bosque en pleno otoño, hojas doradas y luz cálida. Naturaleza y organización para tu hogar.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 3", warranty: GARANTIA, priceCop: 35000, stock: 3, image: prodImg("perchero-bosque-otono"), photos: 3, materials: MATERIALES },
  { id: 18, slug: "perchero-ciudad-central-park", name: "Perchero Ciudad Central Park", categorySlug: "hogar", reference: "PH8", shortDesc: "Skyline urbano junto al parque.", description: "Perchero decorativo con el skyline de la ciudad junto al parque, con herraje central de búho. Estilo urbano para colgar llaves, gorras y accesorios.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 3", warranty: GARANTIA, priceCop: 35000, stock: 3, image: prodImg("perchero-ciudad-central-park"), photos: 3, materials: MATERIALES },
  { id: 19, slug: "perchero-tren-en-la-nieve", name: "Perchero Tren en la Nieve", categorySlug: "hogar", reference: "PH9", shortDesc: "Locomotora clásica entre paisaje nevado.", description: "Perchero decorativo con una locomotora clásica atravesando un paisaje nevado. Una pieza con encanto vintage para tu hogar.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 3", warranty: GARANTIA, priceCop: 35000, stock: 3, image: prodImg("perchero-tren-en-la-nieve"), photos: 3, materials: MATERIALES },
  { id: 20, slug: "perchero-torre-colpatria", name: "Perchero Torre Colpatria Bogotá", categorySlug: "hogar", reference: "PH10", shortDesc: "Atardecer bogotano con la Torre Colpatria.", description: "Perchero decorativo con el atardecer de Bogotá y la Torre Colpatria como protagonista. Para los que llevan la capital en el corazón.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 35000, stock: 3, image: prodImg("perchero-torre-colpatria"), photos: 3, materials: MATERIALES },
  { id: 21, slug: "perchero-puente-manhattan", name: "Perchero Puente de Manhattan", categorySlug: "hogar", reference: "PH11", shortDesc: "El icónico puente entre edificios de ladrillo.", description: "Perchero decorativo con el icónico puente de Manhattan enmarcado entre edificios de ladrillo. Estilo neoyorquino para tu espacio.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 35000, stock: 3, image: prodImg("perchero-puente-manhattan"), photos: 3, materials: MATERIALES },
  { id: 22, slug: "perchero-bahia-skyline", name: "Perchero Bahía Skyline", categorySlug: "hogar", reference: "PH17", shortDesc: "Panorámica de ciudad y bahía, 4 herrajes.", description: "Perchero decorativo panorámico con vista de la ciudad y su bahía. Con cuatro herrajes, ideal para familias y entradas con mucho movimiento.", dimensions: "Aprox. 50 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 4", warranty: GARANTIA, priceCop: 45000, stock: 3, image: prodImg("perchero-bahia-skyline"), photos: 3, materials: MATERIALES },

  // ===== DEDIOS (fotos carpeta /productos/DE DIOS) =====
  { id: 23, slug: "cruz-manos-en-oracion", name: "Cruz Decorativa Manos en Oración", categorySlug: "dedios", reference: "CR1", shortDesc: "Cruz de pared con manos en oración.", description: "Cruz decorativa de pared con imagen de manos en oración y cruz al atardecer. Una pieza de fe para acompañar y proteger tu hogar.", dimensions: "Aprox. 45 x 32 x 1,5 cms", hardware: "Colgante para pared", warranty: GARANTIA, priceCop: 45000, stock: 3, image: prodImg("cruz-manos-en-oracion"), photos: 2, materials: MATERIALES },
  { id: 24, slug: "cruz-amanecer", name: "Cruz Decorativa Amanecer", categorySlug: "dedios", reference: "CR2", shortDesc: "Cruz de pared con amanecer en el calvario.", description: "Cruz decorativa de pared con la imagen de la cruz del calvario al amanecer. Fe y esperanza para decorar tu hogar.", dimensions: "Aprox. 45 x 32 x 1,5 cms", hardware: "Colgante para pared", warranty: GARANTIA, priceCop: 45000, stock: 3, image: prodImg("cruz-amanecer"), photos: 3, materials: MATERIALES },
  { id: 25, slug: "perchero-ultima-cena", name: "Perchero Última Cena", categorySlug: "dedios", reference: "PdD1", shortDesc: "La Última Cena en madera con herrajes.", description: "Perchero decorativo con la imagen de la Última Cena, útil y resiliente. Una pieza clásica de fe para el comedor o la entrada del hogar.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 40000, stock: 3, featured: true, image: prodImg("perchero-ultima-cena"), photos: 3, materials: MATERIALES },
  { id: 26, slug: "perchero-espiritu-santo", name: "Perchero Espíritu Santo", categorySlug: "dedios", reference: "PdD2", shortDesc: "La paloma del Espíritu Santo entre nubes.", description: "Perchero decorativo con la paloma del Espíritu Santo entre nubes doradas. Paz y organización para tu hogar.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 3", warranty: GARANTIA, priceCop: 40000, stock: 3, image: prodImg("perchero-espiritu-santo"), photos: 2, materials: MATERIALES },
  { id: 27, slug: "perchero-biblia-luz", name: "Perchero Biblia Luz Divina", categorySlug: "dedios", reference: "PdD3", shortDesc: "Biblia abierta iluminada por luz divina.", description: "Perchero decorativo con una Biblia abierta iluminada por un rayo de luz. La Palabra siempre presente en tu hogar.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 40000, stock: 3, image: prodImg("perchero-biblia-luz"), photos: 3, materials: MATERIALES },
  { id: 28, slug: "perchero-jesus-en-oracion", name: "Perchero Jesús en Oración", categorySlug: "dedios", reference: "PdD4", shortDesc: "Jesús orando, diseño escalonado.", description: "Perchero decorativo escalonado con la imagen de Jesús en oración. Un diseño diferente que combina fe, arte y funcionalidad.", dimensions: "Aprox. 40 x 15 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 3", warranty: GARANTIA, priceCop: 45000, stock: 3, image: prodImg("perchero-jesus-en-oracion"), photos: 3, materials: MATERIALES },
  { id: 29, slug: "perchero-cruz-del-calvario", name: "Perchero Cruz del Calvario", categorySlug: "dedios", reference: "PdD5", shortDesc: "Cruz al atardecer, diseño escalonado.", description: "Perchero decorativo escalonado con la cruz del calvario al atardecer. Fe y diseño en una pieza única para tu pared.", dimensions: "Aprox. 40 x 15 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 3", warranty: GARANTIA, priceCop: 45000, stock: 3, image: prodImg("perchero-cruz-del-calvario"), photos: 3, materials: MATERIALES },
  { id: 30, slug: "perchero-buen-pastor", name: "Perchero Jesús el Buen Pastor", categorySlug: "dedios", reference: "PdD6", shortDesc: "Jesús el Buen Pastor entre montañas.", description: "Perchero decorativo con la imagen de Jesús el Buen Pastor caminando entre montañas. Compañía y protección para tu hogar.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 40000, stock: 3, image: prodImg("perchero-buen-pastor"), photos: 3, materials: MATERIALES },
  { id: 31, slug: "perchero-en-tus-manos", name: "Perchero En Tus Manos Encomiendo Mi Espíritu", categorySlug: "dedios", reference: "PdD7", shortDesc: "Frase de fe con la imagen de Jesús.", description: "Perchero decorativo con la frase “Padre, en tus manos encomiendo mi espíritu” y la imagen de Jesús. Palabras de fe para cada día.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 40000, stock: 3, image: prodImg("perchero-en-tus-manos"), photos: 3, materials: MATERIALES },
  { id: 32, slug: "perchero-mi-fortaleza", name: "Perchero Jesús Tú Eres Mi Fortaleza", categorySlug: "dedios", reference: "PdD8", shortDesc: "Cruz de madera con frase de fortaleza.", description: "Perchero decorativo con una cruz de madera y la frase “Jesús, Tú eres mi Fortaleza…”. Fuerza y fe para tu hogar.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 40000, stock: 3, image: prodImg("perchero-mi-fortaleza"), photos: 3, materials: MATERIALES },
  { id: 33, slug: "perchero-cruz-atardecer", name: "Perchero Cruz al Atardecer", categorySlug: "dedios", reference: "PdD9", shortDesc: "Cruz al atardecer con versículo bíblico.", description: "Perchero decorativo con la cruz al atardecer y el versículo “Él mismo, en su cuerpo llevó al madero nuestros pecados”. Fe que acompaña y organiza.", dimensions: "Aprox. 40 x 9 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 2", warranty: GARANTIA, priceCop: 40000, stock: 3, featured: true, image: prodImg("perchero-cruz-atardecer"), photos: 3, materials: MATERIALES },

  // ===== GUITARRAS (fotos carpeta /productos/GUITARRAS) =====
  { id: 34, slug: "soporte-guitarra-iron-maiden", name: "Soporte de Guitarra Iron Maiden", categorySlug: "guitarras", reference: "PG1", shortDesc: "Soporte de pared con arte de Iron Maiden.", description: "Soporte de pared para guitarra con arte inspirado en Iron Maiden. Cuelga tu guitarra con estilo y conviértela en parte de la decoración.", dimensions: "Aprox. 20 x 20 x 1,5 cms", hardware: "Soporte acolchado para guitarra · Cant. 1", warranty: GARANTIA, priceCop: 55000, stock: 3, image: prodImg("soporte-guitarra-iron-maiden"), photos: 3, materials: MATERIALES },
  { id: 35, slug: "soporte-guitarra-emblema-rock", name: "Soporte de Guitarra Emblema Rock", categorySlug: "guitarras", reference: "PG2", shortDesc: "Soporte de pared con emblema rockero.", description: "Soporte de pared para guitarra con emblema rockero en blanco sobre madera oscura. Sobrio, resistente y con actitud.", dimensions: "Aprox. 20 x 20 x 1,5 cms", hardware: "Soporte acolchado para guitarra · Cant. 1", warranty: GARANTIA, priceCop: 55000, stock: 3, image: prodImg("soporte-guitarra-emblema-rock"), photos: 3, materials: MATERIALES },
  { id: 36, slug: "soporte-guitarra-acdc", name: "Soporte de Guitarra AC/DC", categorySlug: "guitarras", reference: "PG3", shortDesc: "Soporte de pared con arte de AC/DC.", description: "Soporte de pared para guitarra con arte inspirado en AC/DC. Alta tensión para tu espacio musical.", dimensions: "Aprox. 20 x 20 x 1,5 cms", hardware: "Soporte acolchado para guitarra · Cant. 1", warranty: GARANTIA, priceCop: 55000, stock: 3, featured: true, image: prodImg("soporte-guitarra-acdc"), photos: 3, materials: MATERIALES },
  { id: 37, slug: "soporte-guitarra-soda-stereo", name: "Soporte de Guitarra Soda Stereo", categorySlug: "guitarras", reference: "PG4", shortDesc: "Soporte de pared con arte de Soda Stereo.", description: "Soporte de pared para guitarra con arte inspirado en Soda Stereo. Un clásico del rock en español para tu pared.", dimensions: "Aprox. 20 x 20 x 1,5 cms", hardware: "Soporte acolchado para guitarra · Cant. 1", warranty: GARANTIA, priceCop: 55000, stock: 3, image: prodImg("soporte-guitarra-soda-stereo"), photos: 2, materials: MATERIALES },
  { id: 38, slug: "soporte-guitarra-metallica", name: "Soporte de Guitarra Metallica", categorySlug: "guitarras", reference: "PG6", shortDesc: "Soporte de pared con arte de Metallica.", description: "Soporte de pared para guitarra con arte inspirado en el álbum …And Justice for All de Metallica. Para colgar tu guitarra como pieza de colección.", dimensions: "Aprox. 20 x 20 x 1,5 cms", hardware: "Soporte acolchado para guitarra · Cant. 1", warranty: GARANTIA, priceCop: 55000, stock: 3, image: prodImg("soporte-guitarra-metallica"), photos: 2, materials: MATERIALES },

  // ===== MASCOTAS (fotos carpeta /productos/MASCOTAS) =====
  { id: 39, slug: "perchero-huellas-pms1", name: "Perchero Huellas Clásico", categorySlug: "mascotas", reference: "PMS1", shortDesc: "Huellas sobre fondo dorado, 3 herrajes.", description: "Perchero con diseño de huellas sobre fondo dorado y tres herrajes metálicos. Organiza correas, arneses y accesorios de tu mascota.", dimensions: "Aprox. 40 x 10 x 1,5 cms", hardware: "Herrajes metálicos · Cant. 3", warranty: GARANTIA, priceCop: 28000, stock: 3, image: prodImg("perchero-huellas-pms1"), photos: 1, materials: MATERIALES },
];
