// === Catálogo de productos EN CÓDIGO (Vercel-ready, sin base de datos) ===
// Patrón inspirado en scentualbliss: el catálogo cambia poco, así que vive en
// código. Esto hace que la tienda sea estática/ISR y funcione en Vercel sin DB.
// Lo dinámico (órdenes) va en Supabase.

export interface CatCategory {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  image: string;
}

export interface CatProduct {
  id: number;
  slug: string;
  name: string;
  categorySlug: string;
  reference: string;
  shortDesc: string;
  description: string;
  materials: string;
  dimensions: string;
  hardware: string;
  warranty: string;
  priceCop: number;
  compareAtCop?: number;
  stock: number;
  featured?: boolean;
  isNew?: boolean;
  image: string;
  /** Cantidad de fotos en /img/products: {slug}.webp, {slug}-2.webp, ... */
  photos?: number;
}

const MATERIALES =
  "Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.";

const catImg = (slug: string) => `/img/categories/${slug}.webp`;
const prodImg = (name: string) => `/img/products/${name}.webp`;

export const categories: CatCategory[] = [
  { slug: "dedios", name: "DeDIOS", tagline: "Útiles y Resilientes", description: "Percheros con mensajes e imágenes de fe y esperanza, para acompañar y decorar tu hogar.", image: catImg("dedios") },
  { slug: "hogar", name: "Hogar", tagline: "Útiles y Decorativos", description: "Percheros decorativos con imágenes de paisajes y diferentes temáticas, útiles para colgar accesorios livianos, ofreciendo organización, funcionalidad y decoración en el hogar.", image: catImg("hogar") },
  { slug: "mascotas", name: "Mascotas", tagline: "Útiles y Familiares", description: "Percheros diseñados para los amantes de las mascotas: organiza correas, juguetes y accesorios de tu compañero con estilo.", image: catImg("mascotas") },
  { slug: "moteros", name: "Moteros", tagline: "Útiles y Seguros", description: "Percheros con temática motera para colgar cascos, chaquetas y accesorios de viaje. Vive la pasión por las carreteras.", image: catImg("moteros") },
  { slug: "bike", name: "Bike", tagline: "Útiles y Resilientes", description: "Percheros para ciclistas: organiza cascos, guantes y accesorios de tu bici con diseños llenos de aventura.", image: catImg("bike") },
  { slug: "guitarras", name: "Guitarras", tagline: "Útiles y Cómodos", description: "Percheros inspirados en la música, ideales para colgar accesorios y decorar el espacio de los amantes de la guitarra.", image: catImg("guitarras") },
  { slug: "personalizados", name: "Personalizados", tagline: "Útiles y Prácticos", description: "Percheros hechos a tu medida: nombres, fechas, logos o diseños únicos para regalar o decorar a tu estilo.", image: catImg("personalizados") },
  { slug: "corporativos", name: "Corporativos", tagline: "Útiles y Funcionales", description: "Percheros con la imagen de tu marca o empresa. Detalles corporativos útiles, funcionales y memorables.", image: catImg("corporativos") },
  { slug: "murales", name: "Murales", tagline: "Útiles y Decorativos", description: "Murales decorativos en madera que transforman cualquier pared en un espacio con personalidad y organización.", image: catImg("murales") },
  { slug: "souvenires", name: "Souvenires", tagline: "Útiles y Cómodos", description: "Recuerdos y detalles artesanales en madera, perfectos para sorprender en cualquier ocasión.", image: catImg("souvenires") },
  { slug: "variados", name: "Variados", tagline: "Útiles y Funcionales", description: "Diseños variados para todos los gustos: una selección versátil de percheros artesanales.", image: catImg("variados") },
];

// Catálogo reconstruido desde el inventario oficial
// "INVENTARIO DISPONIBLE PERCHEROS 2026 - WEB.xlsx": código, diseño, medidas,
// herrajes, categoría, precio feria/normal y cantidad son los del documento.
// Solo se publican las referencias que además tienen foto real en
// /productos/nuevosultimos (ground truth de fotos = listado de carpeta, no
// la columna "FOTOS" de la hoja, que no estaba actualizada).
const GARANTIA = "6 meses";
const HERRAJE_DUPLEX = "2 ganchos duplex verticales";
const HERRAJE_DUPLEX_SENCILLO = "2 ganchos duplex verticales + 1 sencillo";
const HERRAJE_CRUZ = "Herraje tipo serrucho (colgante oculto)";
const HERRAJE_GUITARRA = "Soporte ajustable para guitarra";
const HERRAJE_CASCO = "2 soportes rígidos para casco";
const HERRAJE_DUPLEX1_SENCILLO = "1 gancho duplex vertical + 1 sencillo";

export const products: CatProduct[] = [
  // ===== HOGAR (fotos carpeta /productos/nuevosultimos/HOGAR) =====
  { id: 1, slug: "perchero-la-candelaria-bogota", name: "Perchero La Candelaria Bogotá", categorySlug: "hogar", reference: "PH1", shortDesc: "Calles coloniales de La Candelaria, Bogotá.", description: "Perchero decorativo con imagen de las calles coloniales de La Candelaria, en el centro histórico de Bogotá. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 30 x 7,5 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 30000, compareAtCop: 40000, stock: 2, featured: true, image: prodImg("perchero-la-candelaria-bogota"), photos: 3, materials: MATERIALES },
  { id: 2, slug: "perchero-la-candelaria-colores", name: "Perchero La Candelaria Casas de Colores", categorySlug: "hogar", reference: "PH1-1", shortDesc: "Fachadas coloridas del barrio La Candelaria.", description: "Perchero decorativo con las fachadas coloridas del barrio La Candelaria de Bogotá. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 30 x 7,5 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 30000, compareAtCop: 40000, stock: 2, image: prodImg("perchero-la-candelaria-colores"), photos: 3, materials: MATERIALES },
  { id: 3, slug: "perchero-monserrate-bogota", name: "Perchero Monserrate Bogotá", categorySlug: "hogar", reference: "PH2", shortDesc: "El santuario de Monserrate sobre Bogotá.", description: "Perchero decorativo con vista panorámica del santuario de Monserrate y la ciudad de Bogotá. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 29,5 x 8 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 25000, compareAtCop: 35000, stock: 2, featured: true, image: prodImg("perchero-monserrate-bogota"), photos: 3, materials: MATERIALES },
  { id: 4, slug: "perchero-mandalas", name: "Perchero Mandalas", categorySlug: "hogar", reference: "PH3", shortDesc: "Mandalas multicolores llenos de energía.", description: "Perchero decorativo con mandalas multicolores, ideal para dar vida y energía a cualquier espacio. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 30 x 7,5 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 25000, compareAtCop: 35000, stock: 2, image: prodImg("perchero-mandalas"), photos: 3, materials: MATERIALES },
  { id: 5, slug: "perchero-plaza-de-bolivar", name: "Perchero Plaza de Bolívar Bogotá", categorySlug: "hogar", reference: "PH4", shortDesc: "La Catedral y la Plaza de Bolívar de Bogotá.", description: "Perchero decorativo con la Plaza de Bolívar y la Catedral Primada de Bogotá. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 30 x 7,5 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 25000, stock: 1, featured: true, image: prodImg("perchero-plaza-de-bolivar"), photos: 3, materials: MATERIALES },
  { id: 6, slug: "perchero-muelle-paisaje-azul", name: "Perchero Muelle Paisaje Azul", categorySlug: "hogar", reference: "PH5", shortDesc: "Muelle nocturno en tonos azules.", description: "Perchero decorativo con un muelle en tonos azules. Diseño tallado directamente en madera, pieza única artesanal.", dimensions: "Aprox. 37,5 x 6 x 1,2 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 30000, compareAtCop: 40000, stock: 1, featured: true, image: prodImg("perchero-muelle-paisaje-azul"), photos: 3, materials: MATERIALES },
  { id: 7, slug: "perchero-atardecer-en-bici", name: "Perchero Atardecer en Bici", categorySlug: "hogar", reference: "PH6", shortDesc: "Siluetas de ciclistas al caer el sol.", description: "Perchero decorativo con siluetas de ciclistas al atardecer, perfecto para los amantes de la bici. Diseño tallado directamente en madera.", dimensions: "Aprox. 37,5 x 6 x 1,2 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 30000, compareAtCop: 40000, stock: 1, image: prodImg("perchero-atardecer-en-bici"), photos: 3, materials: MATERIALES },
  { id: 8, slug: "perchero-bosque", name: "Perchero Bosque", categorySlug: "hogar", reference: "PH7", shortDesc: "Bosque en tonos dorados y luz cálida.", description: "Perchero decorativo con un bosque en luz cálida, naturaleza para tu hogar. Diseño tallado directamente en madera.", dimensions: "Aprox. 37,5 x 6 x 1,2 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 30000, compareAtCop: 40000, stock: 1, image: prodImg("perchero-bosque"), photos: 3, materials: MATERIALES },
  { id: 9, slug: "perchero-ciudad-y-golfo", name: "Perchero Paisaje Ciudad y Golfo", categorySlug: "hogar", reference: "PH8", shortDesc: "Skyline urbano junto al golfo.", description: "Perchero decorativo con el skyline de la ciudad junto al golfo. Estilo urbano para colgar llaves, gorras y accesorios. Diseño tallado directamente en madera.", dimensions: "Aprox. 37,5 x 6 x 1,2 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 30000, compareAtCop: 40000, stock: 1, image: prodImg("perchero-ciudad-y-golfo"), photos: 3, materials: MATERIALES },
  { id: 10, slug: "perchero-tren-epoca-de-nieve", name: "Perchero Tren en Época de Nieve", categorySlug: "hogar", reference: "PH9", shortDesc: "Locomotora clásica entre paisaje nevado.", description: "Perchero decorativo con una locomotora clásica atravesando un paisaje nevado. Diseño tallado directamente en madera, encanto vintage.", dimensions: "Aprox. 37,5 x 6 x 1,2 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 30000, compareAtCop: 40000, stock: 1, image: prodImg("perchero-tren-epoca-de-nieve"), photos: 3, materials: MATERIALES },
  { id: 11, slug: "perchero-torre-colpatria", name: "Perchero Torre Colpatria Bogotá", categorySlug: "hogar", reference: "PH10", shortDesc: "Atardecer bogotano con la Torre Colpatria.", description: "Perchero decorativo con el atardecer de Bogotá y la Torre Colpatria como protagonista. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 30 x 8 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 25000, compareAtCop: 35000, stock: 1, featured: true, image: prodImg("perchero-torre-colpatria"), photos: 3, materials: MATERIALES },
  { id: 12, slug: "perchero-puente-manhattan", name: "Perchero Puente de Manhattan", categorySlug: "hogar", reference: "PH11", shortDesc: "El icónico puente entre edificios de ladrillo.", description: "Perchero decorativo con el icónico puente de Manhattan. Diseño combinando impresión full color y talla en madera, estilo neoyorquino.", dimensions: "Aprox. 30 x 8 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 25000, compareAtCop: 35000, stock: 1, image: prodImg("perchero-puente-manhattan"), photos: 3, materials: MATERIALES },
  { id: 13, slug: "perchero-bahia-skyline", name: "Perchero Bahía Skyline", categorySlug: "hogar", reference: "PH17", shortDesc: "Panorámica de ciudad y bahía, 4 herrajes.", description: "Perchero decorativo panorámico con vista de la ciudad y su bahía. Con cuatro herrajes, ideal para familias y entradas con mucho movimiento. Diseño combinando impresión full color y talla en madera.", dimensions: "Aprox. 62 x 8 x 1,5 cms", hardware: "4 ganchos duplex verticales", warranty: GARANTIA, priceCop: 45000, compareAtCop: 55000, stock: 1, image: prodImg("perchero-bahia-skyline"), photos: 3, materials: MATERIALES },
  { id: 47, slug: "perchero-atardecer-canoa", name: "Perchero Atardecer en Canoa", categorySlug: "hogar", reference: "PH14", shortDesc: "Canoa deslizándose bajo el atardecer.", description: "Perchero decorativo con una canoa deslizándose sobre el agua bajo un atardecer. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 37,5 x 6 x 1,2 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 30000, compareAtCop: 40000, stock: 1, isNew: true, image: prodImg("perchero-atardecer-canoa"), photos: 3, materials: MATERIALES },
  { id: 48, slug: "perchero-puente-madera-pantano", name: "Perchero Puente de Madera en el Pantano", categorySlug: "hogar", reference: "PH15", shortDesc: "Puente de madera atravesando un pantano.", description: "Perchero decorativo con un puente de madera atravesando un pantano. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 37,5 x 6 x 1,2 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 30000, compareAtCop: 40000, stock: 1, isNew: true, image: prodImg("perchero-puente-madera-pantano"), photos: 3, materials: MATERIALES },
  { id: 49, slug: "perchero-atardecer-rojizo", name: "Perchero Atardecer Rojizo", categorySlug: "hogar", reference: "PH16", shortDesc: "Paisaje en tonos rojizos de atardecer.", description: "Perchero decorativo con un paisaje en tonos rojizos de atardecer. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 37,5 x 14 x 1,2 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 35000, compareAtCop: 45000, stock: 1, isNew: true, image: prodImg("perchero-atardecer-rojizo"), photos: 3, materials: MATERIALES },
  { id: 50, slug: "perchero-casa-en-el-bosque", name: "Perchero Casa en el Bosque", categorySlug: "hogar", reference: "PH18", shortDesc: "Cabaña rústica entre árboles de otoño.", description: "Perchero decorativo con una cabaña rústica entre árboles de otoño. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 23 x 10 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 15000, compareAtCop: 20000, stock: 1, isNew: true, image: prodImg("perchero-casa-en-el-bosque"), photos: 3, materials: MATERIALES },
  { id: 51, slug: "perchero-camino-madera-bosque", name: "Perchero Camino de Madera en el Bosque", categorySlug: "hogar", reference: "PH19", shortDesc: "Pasarela de madera entre hojas de otoño.", description: "Perchero decorativo con una pasarela de madera entre hojas de otoño. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 23 x 10 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 15000, compareAtCop: 20000, stock: 1, isNew: true, image: prodImg("perchero-camino-madera-bosque"), photos: 3, materials: MATERIALES },
  { id: 52, slug: "perchero-cerca-blanca-bosque", name: "Perchero Cerca Blanca en el Bosque", categorySlug: "hogar", reference: "PH20", shortDesc: "Cerca blanca entre árboles de otoño.", description: "Perchero decorativo con una cerca blanca entre árboles de otoño. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 23 x 10 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 15000, compareAtCop: 20000, stock: 1, isNew: true, image: prodImg("perchero-cerca-blanca-bosque"), photos: 3, materials: MATERIALES },

  // ===== DEDIOS (fotos carpeta /productos/nuevosultimos/DE DIOS) =====
  { id: 14, slug: "cruz-manos-en-oracion", name: "Cruz Decorativa Manos en Oración", categorySlug: "variados", reference: "PVCR1", shortDesc: "Cruz de pared con manos en oración.", description: "Cruz decorativa de pared con imagen de manos en oración y cruz al atardecer. Diseño en impresión de vinilo full color sobre madera. Una pieza de fe para acompañar tu hogar.", dimensions: "Aprox. 45 x 32 x 1,5 cms", hardware: HERRAJE_CRUZ, warranty: GARANTIA, priceCop: 55000, compareAtCop: 65000, stock: 1, image: prodImg("cruz-manos-en-oracion"), photos: 2, materials: MATERIALES },
  { id: 15, slug: "cruz-amanecer", name: "Cruz Decorativa Cruz del Monte", categorySlug: "variados", reference: "PVCR2", shortDesc: "Cruz de pared con amanecer en el calvario.", description: "Cruz decorativa de pared con la imagen de la cruz del calvario al amanecer. Diseño en impresión de vinilo full color sobre madera. Fe y esperanza para tu hogar.", dimensions: "Aprox. 45 x 32 x 1,5 cms", hardware: HERRAJE_CRUZ, warranty: GARANTIA, priceCop: 65000, compareAtCop: 75000, stock: 1, image: prodImg("cruz-amanecer"), photos: 3, materials: MATERIALES },
  { id: 16, slug: "perchero-ultima-cena", name: "Perchero Última Cena", categorySlug: "dedios", reference: "PdD1", shortDesc: "La Última Cena tallada en madera.", description: "Perchero decorativo con la imagen de la Última Cena. Diseño tallado directamente en madera. Una pieza clásica de fe para el comedor o la entrada del hogar.", dimensions: "Aprox. 34 x 7 x 2 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 25000, compareAtCop: 35000, stock: 2, featured: true, image: prodImg("perchero-ultima-cena"), photos: 3, materials: MATERIALES },
  { id: 17, slug: "perchero-espiritu-santo", name: "Perchero Espíritu Santo", categorySlug: "dedios", reference: "PdD2", shortDesc: "La paloma del Espíritu Santo entre nubes.", description: "Perchero decorativo con la paloma del Espíritu Santo entre nubes. Diseño tallado directamente en madera. Paz y organización para tu hogar.", dimensions: "Aprox. 30 x 7,5 x 1,5 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 30000, compareAtCop: 40000, stock: 2, featured: true, image: prodImg("perchero-espiritu-santo"), photos: 2, materials: MATERIALES },
  { id: 18, slug: "perchero-biblia-luz", name: "Perchero La Biblia", categorySlug: "dedios", reference: "PdD3", shortDesc: "Biblia abierta iluminada por luz divina.", description: "Perchero decorativo con una Biblia abierta iluminada por un rayo de luz. Diseño en impresión de vinilo full color sobre madera. La Palabra siempre presente en tu hogar.", dimensions: "Aprox. 30 x 7,5 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 25000, compareAtCop: 35000, stock: 1, image: prodImg("perchero-biblia-luz"), photos: 3, materials: MATERIALES },
  { id: 19, slug: "perchero-jesus-viendo-la-ciudad", name: "Perchero Jesús Viendo la Ciudad", categorySlug: "dedios", reference: "PdD4", shortDesc: "Jesús sentado, contemplando la ciudad.", description: "Perchero decorativo con la imagen de Jesús sentado, viendo la ciudad. Diseño combinando impresión full color y talla en madera.", dimensions: "Aprox. 30 x 10 x 1,5 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 35000, compareAtCop: 45000, stock: 1, image: prodImg("perchero-jesus-viendo-la-ciudad"), photos: 3, materials: MATERIALES },
  { id: 20, slug: "perchero-cruz-de-rodillas", name: "Perchero La Cruz y De Rodillas", categorySlug: "dedios", reference: "PdD5", shortDesc: "La cruz y una figura de rodillas en oración.", description: "Perchero decorativo con la cruz y una figura de rodillas en oración. Diseño combinando impresión full color y talla en madera.", dimensions: "Aprox. 30 x 10 x 1,5 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 35000, compareAtCop: 45000, stock: 1, image: prodImg("perchero-cruz-de-rodillas"), photos: 3, materials: MATERIALES },
  { id: 21, slug: "perchero-buen-pastor", name: "Perchero Jesús Pastor", categorySlug: "dedios", reference: "PdD6", shortDesc: "Jesús el Buen Pastor entre montañas.", description: "Perchero decorativo con la imagen de Jesús el Buen Pastor caminando entre montañas. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 30 x 7,5 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 25000, compareAtCop: 35000, stock: 2, image: prodImg("perchero-buen-pastor"), photos: 3, materials: MATERIALES },
  { id: 22, slug: "perchero-en-tus-manos", name: "Perchero Padre en Tus Manos Encomiendo Mi Espíritu", categorySlug: "dedios", reference: "PdD7", shortDesc: "Frase de fe con la imagen de Jesús.", description: "Perchero decorativo con la frase “Padre, en tus manos encomiendo mi espíritu” y la imagen de Jesús. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 30 x 7,5 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 25000, compareAtCop: 35000, stock: 2, image: prodImg("perchero-en-tus-manos"), photos: 3, materials: MATERIALES },
  { id: 23, slug: "perchero-mi-fortaleza", name: "Perchero Cruz con Rosario — Tú Eres Mi Fortaleza", categorySlug: "dedios", reference: "PdD8", shortDesc: "Cruz con rosario y frase de fortaleza.", description: "Perchero decorativo con una cruz, un rosario y la frase “Tú eres mi Fortaleza”. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 30 x 8 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 25000, compareAtCop: 35000, stock: 1, image: prodImg("perchero-mi-fortaleza"), photos: 3, materials: MATERIALES },
  { id: 24, slug: "perchero-cruz-al-madero", name: "Perchero Cruz al Madero Nuestros Pecados", categorySlug: "dedios", reference: "PdD9", shortDesc: "Cruz al atardecer con versículo bíblico.", description: "Perchero decorativo con la cruz al atardecer y el versículo “Él mismo, en su cuerpo, llevó al madero nuestros pecados”. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 30 x 8 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 25000, compareAtCop: 35000, stock: 2, featured: true, image: prodImg("perchero-cruz-al-madero"), photos: 3, materials: MATERIALES },

  // ===== GUITARRAS (fotos carpeta /productos/nuevosultimos/GUITARRAS) =====
  { id: 25, slug: "soporte-guitarra-iron-maiden", name: "Soporte de Guitarra Iron Maiden", categorySlug: "guitarras", reference: "PG1", shortDesc: "Soporte de pared con arte de Iron Maiden.", description: "Soporte de pared para guitarra con arte inspirado en Iron Maiden. Diseño en impresión de vinilo full color sobre madera. Cuelga tu guitarra como pieza de colección.", dimensions: "Aprox. 19 x 19 x 1,5 cms", hardware: HERRAJE_GUITARRA, warranty: GARANTIA, priceCop: 45000, compareAtCop: 55000, stock: 2, featured: true, image: prodImg("soporte-guitarra-iron-maiden"), photos: 3, materials: MATERIALES },
  { id: 26, slug: "soporte-guitarra-heroes-del-silencio", name: "Soporte de Guitarra Héroes del Silencio", categorySlug: "guitarras", reference: "PG2", shortDesc: "Soporte de pared con isotipo de Héroes del Silencio.", description: "Soporte de pared para guitarra con el isotipo de Héroes del Silencio. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 19 x 19 x 1,5 cms", hardware: HERRAJE_GUITARRA, warranty: GARANTIA, priceCop: 45000, compareAtCop: 55000, stock: 2, image: prodImg("soporte-guitarra-heroes-del-silencio"), photos: 3, materials: MATERIALES },
  { id: 27, slug: "soporte-guitarra-acdc", name: "Soporte de Guitarra AC/DC", categorySlug: "guitarras", reference: "PG3", shortDesc: "Soporte de pared con arte de AC/DC.", description: "Soporte de pared para guitarra con arte inspirado en AC/DC. Diseño en impresión de vinilo full color sobre madera. Alta tensión para tu espacio musical.", dimensions: "Aprox. 19 x 19 x 1,5 cms", hardware: HERRAJE_GUITARRA, warranty: GARANTIA, priceCop: 45000, compareAtCop: 55000, stock: 1, featured: true, image: prodImg("soporte-guitarra-acdc"), photos: 3, materials: MATERIALES },
  { id: 28, slug: "soporte-guitarra-soda-stereo", name: "Soporte de Guitarra Soda Stereo", categorySlug: "guitarras", reference: "PG4", shortDesc: "Soporte de pared con arte de Soda Stereo.", description: "Soporte de pared para guitarra con arte inspirado en Soda Stereo. Diseño en impresión de vinilo full color sobre madera. Un clásico del rock en español.", dimensions: "Aprox. 19 x 19 x 1,5 cms", hardware: HERRAJE_GUITARRA, warranty: GARANTIA, priceCop: 45000, compareAtCop: 55000, stock: 1, image: prodImg("soporte-guitarra-soda-stereo"), photos: 2, materials: MATERIALES },
  { id: 29, slug: "soporte-guitarra-metallica", name: "Soporte de Guitarra Metallica", categorySlug: "guitarras", reference: "PG6", shortDesc: "Soporte de pared con arte de Metallica.", description: "Soporte de pared para guitarra con arte inspirado en Metallica. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 19 x 19 x 1,5 cms", hardware: HERRAJE_GUITARRA, warranty: GARANTIA, priceCop: 45000, compareAtCop: 55000, stock: 1, image: prodImg("soporte-guitarra-metallica"), photos: 2, materials: MATERIALES },

  // ===== MASCOTAS (fotos carpeta /productos/nuevosultimos/MASCOTAS) =====
  { id: 30, slug: "perchero-huellas-clasico", name: "Perchero Huellas Clásico", categorySlug: "mascotas", reference: "PMS1", shortDesc: "Huellas sobre fondo dorado, 3 herrajes.", description: "Perchero con diseño de huellas sobre fondo dorado. Diseño en impresión de vinilo full color sobre madera. Organiza correas, arneses y accesorios de tu mascota.", dimensions: "Aprox. 30 x 7,5 x 1,5 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 30000, compareAtCop: 40000, stock: 1, image: prodImg("perchero-huellas-clasico"), photos: 3, materials: MATERIALES },
  { id: 40, slug: "perchero-oso-acostado", name: "Perchero Oso Acostado", categorySlug: "mascotas", reference: "PMS2", shortDesc: "Oso pardo recostado frente a la montaña.", description: "Perchero decorativo con un oso pardo recostado frente a un paisaje de montaña. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 19,5 x 8,5 x 1,5 cms", hardware: HERRAJE_DUPLEX1_SENCILLO, warranty: GARANTIA, priceCop: 12000, compareAtCop: 20000, stock: 1, isNew: true, image: prodImg("perchero-oso-acostado"), photos: 3, materials: MATERIALES },
  { id: 41, slug: "perchero-aguila", name: "Perchero Águila", categorySlug: "mascotas", reference: "PMS3", shortDesc: "Águila americana en pleno vuelo.", description: "Perchero decorativo con un águila americana en pleno vuelo. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 19,5 x 8,5 x 1,5 cms", hardware: HERRAJE_DUPLEX1_SENCILLO, warranty: GARANTIA, priceCop: 12000, compareAtCop: 20000, stock: 1, isNew: true, image: prodImg("perchero-aguila"), photos: 3, materials: MATERIALES },
  { id: 42, slug: "perchero-siluetas-mascota-duena", name: "Perchero Siluetas Mascota y Dueña", categorySlug: "mascotas", reference: "PMS4", shortDesc: "Siluetas de mascota y dueña al atardecer.", description: "Perchero decorativo con las siluetas de una mascota y su dueña. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 19,5 x 8,5 x 1,5 cms", hardware: HERRAJE_DUPLEX1_SENCILLO, warranty: GARANTIA, priceCop: 12000, compareAtCop: 20000, stock: 1, isNew: true, image: prodImg("perchero-siluetas-mascota-duena"), photos: 3, materials: MATERIALES },
  { id: 43, slug: "perchero-atardecer-playa-mascota-dueno", name: "Perchero Atardecer en la Playa Mascota y Dueño", categorySlug: "mascotas", reference: "PMS5", shortDesc: "Mascota y dueño contemplando el atardecer en la playa.", description: "Perchero decorativo con la silueta de una mascota y su dueño contemplando el atardecer en la playa. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 19,5 x 8,5 x 1,5 cms", hardware: HERRAJE_DUPLEX1_SENCILLO, warranty: GARANTIA, priceCop: 12000, compareAtCop: 20000, stock: 1, isNew: true, image: prodImg("perchero-atardecer-playa-mascota-dueno"), photos: 3, materials: MATERIALES },
  { id: 44, slug: "perchero-cascada-paisaje", name: "Perchero Cascada Paisaje", categorySlug: "mascotas", reference: "PMS6", shortDesc: "Cascada gemela en medio del bosque.", description: "Perchero decorativo con una cascada gemela en medio del bosque. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 24 x 10 x 1,5 cms", hardware: HERRAJE_DUPLEX1_SENCILLO, warranty: GARANTIA, priceCop: 12000, compareAtCop: 20000, stock: 1, isNew: true, image: prodImg("perchero-cascada-paisaje"), photos: 3, materials: MATERIALES },
  { id: 45, slug: "perchero-labrador-y-gato-cachorros", name: "Perchero Labrador y Gato Cachorros", categorySlug: "mascotas", reference: "PMS7", shortDesc: "Cachorro y gatito entre flores rosadas.", description: "Perchero decorativo con un cachorro labrador y un gatito entre flores rosadas. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 30 x 7,5 x 1,5 cms", hardware: HERRAJE_DUPLEX1_SENCILLO, warranty: GARANTIA, priceCop: 20000, compareAtCop: 30000, stock: 1, isNew: true, image: prodImg("perchero-labrador-y-gato-cachorros"), photos: 3, materials: MATERIALES },
  { id: 46, slug: "perchero-lobos-aullando", name: "Perchero Lobos Aullando", categorySlug: "mascotas", reference: "PMS8", shortDesc: "Lobo aullando bajo la luna llena.", description: "Perchero decorativo con un lobo aullando bajo la luna llena. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 29,5 x 8 x 1,5 cms", hardware: HERRAJE_DUPLEX, warranty: GARANTIA, priceCop: 25000, compareAtCop: 35000, stock: 1, isNew: true, image: prodImg("perchero-lobos-aullando"), photos: 3, materials: MATERIALES },

  // ===== MOTEROS (fotos carpeta /productos/nuevosultimos/MOTEROS) =====
  // Percheros/organizadores de casco y chaqueta, 5 fotos c/u (pieza vacía +
  // en uso con casco, ángulos distintos). Recién fotografiados: marcados isNew.
  { id: 31, slug: "perchero-guitarra-en-llamas", name: "Perchero Guitarra en Llamas", categorySlug: "moteros", reference: "PMTV1", shortDesc: "Organizador de casco con guitarra en llamas.", description: "Perchero organizador de casco y chaqueta con una guitarra envuelta en llamas. Diseño tallado directamente en madera. Sostiene el casco con firmeza gracias a sus dos soportes rígidos.", dimensions: "Aprox. 73 x 10 x 1,5 cms", hardware: HERRAJE_CASCO, warranty: GARANTIA, priceCop: 70000, compareAtCop: 80000, stock: 1, isNew: true, featured: true, image: prodImg("perchero-guitarra-en-llamas"), photos: 5, materials: MATERIALES },
  { id: 32, slug: "perchero-moto-tren-delantero", name: "Perchero Moto Tren Delantero", categorySlug: "moteros", reference: "PMTV2", shortDesc: "Organizador de casco con vista frontal de moto.", description: "Perchero organizador de casco y chaqueta con la vista frontal de una motocicleta al atardecer. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 75 x 11 x 1,5 cms", hardware: HERRAJE_CASCO, warranty: GARANTIA, priceCop: 50000, compareAtCop: 80000, stock: 1, isNew: true, image: prodImg("perchero-moto-tren-delantero"), photos: 5, materials: MATERIALES },
  { id: 33, slug: "perchero-motero-fondo-amarillo", name: "Perchero Motero Fondo Amarillo", categorySlug: "moteros", reference: "PMTV3", shortDesc: "Motero de frente sobre fondo amarillo atardecer.", description: "Perchero organizador de casco y chaqueta con un motero de frente sobre un fondo amarillo de atardecer. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 75 x 11 x 1,5 cms", hardware: HERRAJE_CASCO, warranty: GARANTIA, priceCop: 50000, compareAtCop: 80000, stock: 1, isNew: true, image: prodImg("perchero-motero-fondo-amarillo"), photos: 5, materials: MATERIALES },
  { id: 34, slug: "perchero-motero-aprilia", name: "Perchero Motero Aprilia", categorySlug: "moteros", reference: "PMTV4", shortDesc: "Motero de frente con moto Aprilia.", description: "Perchero organizador de casco y chaqueta con un motero de frente sobre una Aprilia. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 73 x 10 x 1,5 cms", hardware: HERRAJE_CASCO, warranty: GARANTIA, priceCop: 60000, compareAtCop: 70000, stock: 1, isNew: true, image: prodImg("perchero-motero-aprilia"), photos: 5, materials: MATERIALES },
  { id: 35, slug: "perchero-helicoptero", name: "Perchero Helicóptero", categorySlug: "moteros", reference: "PMTV5", shortDesc: "Helicóptero sobrevolando la ciudad al atardecer.", description: "Perchero organizador de casco y chaqueta con un helicóptero sobrevolando la ciudad al atardecer. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 73 x 10 x 1,5 cms", hardware: HERRAJE_CASCO, warranty: GARANTIA, priceCop: 70000, compareAtCop: 80000, stock: 1, isNew: true, featured: true, image: prodImg("perchero-helicoptero"), photos: 5, materials: MATERIALES },
  { id: 36, slug: "perchero-escudo-nacional", name: "Perchero Escudo Atlético Nacional", categorySlug: "moteros", reference: "PMTV6", shortDesc: "Escudo de Atlético Nacional sobre fondo verde.", description: "Perchero organizador de casco y chaqueta con el escudo de Atlético Nacional. Diseño en impresión de vinilo full color sobre madera. Para los hinchas verdolagas.", dimensions: "Aprox. 73 x 10 x 1,5 cms", hardware: HERRAJE_CASCO, warranty: GARANTIA, priceCop: 60000, compareAtCop: 70000, stock: 1, isNew: true, image: prodImg("perchero-escudo-nacional"), photos: 5, materials: MATERIALES },
  { id: 37, slug: "perchero-escudo-millonarios", name: "Perchero Escudo Millonarios", categorySlug: "moteros", reference: "PMTV7", shortDesc: "Escudo de Millonarios F.C.", description: "Perchero organizador de casco y chaqueta con el escudo de Millonarios F.C. Diseño en impresión de vinilo full color sobre madera. Para los hinchas del embajador.", dimensions: "Aprox. 73 x 10 x 1,5 cms", hardware: HERRAJE_CASCO, warranty: GARANTIA, priceCop: 60000, compareAtCop: 70000, stock: 1, isNew: true, image: prodImg("perchero-escudo-millonarios"), photos: 5, materials: MATERIALES },
  { id: 38, slug: "perchero-flores-rosadas", name: "Perchero Flores Rosadas", categorySlug: "moteros", reference: "PMTV8", shortDesc: "Mandala floral en tonos rosados.", description: "Perchero organizador de casco y chaqueta con un mandala floral en tonos rosados. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 73 x 8 x 1,5 cms", hardware: HERRAJE_CASCO, warranty: GARANTIA, priceCop: 60000, compareAtCop: 70000, stock: 1, isNew: true, image: prodImg("perchero-flores-rosadas"), photos: 5, materials: MATERIALES },
  { id: 39, slug: "perchero-tren-bajo-el-agua", name: "Perchero Tren Bajo el Agua", categorySlug: "moteros", reference: "PMTV9", shortDesc: "Locomotora de vapor entre reflejos de agua.", description: "Perchero organizador de casco y chaqueta con una locomotora de vapor entre reflejos de agua. Diseño tallado directamente en madera.", dimensions: "Aprox. 70 x 12 x 1,5 cms", hardware: HERRAJE_CASCO, warranty: GARANTIA, priceCop: 70000, compareAtCop: 80000, stock: 1, isNew: true, image: prodImg("perchero-tren-bajo-el-agua"), photos: 5, materials: MATERIALES },
  { id: 53, slug: "perchero-harley-davidson-desierto", name: "Perchero Harley Davidson Desierto", categorySlug: "moteros", reference: "PMTH1", shortDesc: "Harley Davidson chopper en el desierto.", description: "Perchero organizador de casco y chaqueta con una Harley Davidson chopper en el desierto. Diseño en impresión fotográfica full color sobre madera.", dimensions: "Aprox. 76 x 11 x 1,5 cms", hardware: HERRAJE_CASCO, warranty: GARANTIA, priceCop: 70000, compareAtCop: 80000, stock: 1, isNew: true, image: prodImg("perchero-harley-davidson-desierto"), photos: 5, materials: MATERIALES },
  { id: 54, slug: "perchero-ciudad-paisaje-abstracto", name: "Perchero Ciudad Paisaje Abstracto", categorySlug: "moteros", reference: "PMTH2", shortDesc: "Skyline urbano en estilo abstracto.", description: "Perchero organizador de casco y chaqueta con un skyline urbano en estilo abstracto. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 73 x 10 x 1,5 cms", hardware: HERRAJE_CASCO, warranty: GARANTIA, priceCop: 70000, compareAtCop: 80000, stock: 1, isNew: true, image: prodImg("perchero-ciudad-paisaje-abstracto"), photos: 5, materials: MATERIALES },
  { id: 55, slug: "perchero-moto-paisaje-carretera", name: "Perchero Moto Paisaje Carretera", categorySlug: "moteros", reference: "PMTH4", shortDesc: "Motocicleta en la carretera abierta.", description: "Perchero organizador de casco y chaqueta con una motocicleta en plena carretera abierta. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 70 x 12 x 1,5 cms", hardware: HERRAJE_CASCO, warranty: GARANTIA, priceCop: 55000, compareAtCop: 70000, stock: 1, isNew: true, image: prodImg("perchero-moto-paisaje-carretera"), photos: 5, materials: MATERIALES },
  { id: 56, slug: "perchero-ghost-rider", name: "Perchero Ghost Rider", categorySlug: "moteros", reference: "PMTH5", shortDesc: "El Motorista Fantasma envuelto en llamas.", description: "Perchero organizador de casco y chaqueta con el Motorista Fantasma (Ghost Rider) envuelto en llamas. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 37,5 x 10 x 1,5 cms", hardware: "1 soporte rígido para casco + 2 ganchos sencillos", warranty: GARANTIA, priceCop: 45000, compareAtCop: 60000, stock: 1, isNew: true, image: prodImg("perchero-ghost-rider"), photos: 3, materials: MATERIALES },
  { id: 57, slug: "perchero-harley-davidson-paisaje", name: "Perchero Harley Davidson Paisaje", categorySlug: "moteros", reference: "PMTH6", shortDesc: "Harley Davidson entre montañas y desierto.", description: "Perchero organizador de casco y chaqueta con una Harley Davidson entre montañas y desierto. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 37,5 x 10 x 1,5 cms", hardware: "1 soporte rígido para casco + 1 gancho duplex vertical", warranty: GARANTIA, priceCop: 45000, compareAtCop: 60000, stock: 1, isNew: true, image: prodImg("perchero-harley-davidson-paisaje"), photos: 3, materials: MATERIALES },

  // ===== BIKE (fotos carpeta /productos/nuevosultimos/BIKE) =====
  { id: 58, slug: "perchero-ciclistas-atardecer", name: "Perchero Ciclistas al Atardecer", categorySlug: "bike", reference: "PB1", shortDesc: "Dos ciclistas rodando bajo el atardecer.", description: "Perchero decorativo con las siluetas de dos ciclistas rodando bajo el atardecer. Diseño en impresión de vinilo full color sobre madera.", dimensions: "Aprox. 37,5 x 7 x 1,5 cms", hardware: HERRAJE_DUPLEX_SENCILLO, warranty: GARANTIA, priceCop: 25000, compareAtCop: 35000, stock: 1, isNew: true, image: prodImg("perchero-ciclistas-atardecer"), photos: 3, materials: MATERIALES },

  // ===== VARIADOS (fotos carpeta /productos/nuevosultimos/VARIADOS) =====
  // Cruces decorativas de pared (herraje tipo serrucho, colgante oculto).
  { id: 59, slug: "cruz-corona-de-espinas", name: "Cruz Decorativa Corona de Espinas", categorySlug: "variados", reference: "PVCR3", shortDesc: "Cristo grabado en madera con corona de espinas.", description: "Cruz decorativa de pared con la figura de Cristo grabada en madera y corona de espinas. Pieza artesanal en corte láser.", dimensions: "Aprox. 29 x 21 x 4,5 x 0,5 cms", hardware: HERRAJE_CRUZ, warranty: GARANTIA, priceCop: 15000, compareAtCop: 25000, stock: 1, isNew: true, image: prodImg("cruz-corona-de-espinas"), photos: 3, materials: MATERIALES },
  { id: 60, slug: "cruz-corona-de-espinas-2", name: "Cruz Decorativa Corona de Espinas II", categorySlug: "variados", reference: "PVCR4", shortDesc: "Cristo grabado en madera con corona de espinas.", description: "Cruz decorativa de pared con la figura de Cristo grabada en madera y corona de espinas. Pieza artesanal en corte láser.", dimensions: "Aprox. 29 x 21 x 4,5 x 0,5 cms", hardware: HERRAJE_CRUZ, warranty: GARANTIA, priceCop: 15000, compareAtCop: 25000, stock: 1, isNew: true, image: prodImg("cruz-corona-de-espinas-2"), photos: 3, materials: MATERIALES },
  { id: 61, slug: "cruz-rostro-jesus-base", name: "Cruz Decorativa Rostro de Jesús con Base", categorySlug: "variados", reference: "PVCR5", shortDesc: "Rostro de Jesús con corona de espinas, con base.", description: "Cruz decorativa con el rostro de Jesús y corona de espinas grabados en madera, incluye base de pie. Pieza artesanal en corte láser.", dimensions: "Aprox. 29 x 21 x 4,5 x 0,5 cms", hardware: HERRAJE_CRUZ, warranty: GARANTIA, priceCop: 18000, compareAtCop: 28000, stock: 1, isNew: true, image: prodImg("cruz-rostro-jesus-base"), photos: 3, materials: MATERIALES },
  { id: 62, slug: "cruz-calvario-base", name: "Cruz Decorativa Calvario con Base", categorySlug: "variados", reference: "PVCR6", shortDesc: "Escena de la resurrección, con base.", description: "Cruz decorativa con la escena de la resurrección grabada en madera, incluye base de pie. Pieza artesanal en corte láser.", dimensions: "Aprox. 29 x 21 x 4,5 x 0,5 cms", hardware: HERRAJE_CRUZ, warranty: GARANTIA, priceCop: 18000, compareAtCop: 28000, stock: 1, isNew: true, image: prodImg("cruz-calvario-base"), photos: 4, materials: MATERIALES },
];
