-- =====================================================
-- Percheros Decorativos — Migración de catálogo (lote 2026-08-27)
-- Ejecutar en: Supabase Dashboard → SQL Editor
--
-- Contenido:
--   1) 23 productos nuevos (fotos entregadas 27ago2026,
--      Excel "INVENTARIO DISPONIBLE PERCHEROS 2026 - WEB 2.xlsx").
--   2) Reclasifica CR1/CR2 (ids 14 y 15) de "dedios" a "variados",
--      igual que el Excel actualizado las mueve a PVCR1/PVCR2.
--   3) Amplía las fotos de PMS1 (Perchero Huellas Clásico) de 1 a 3.
-- =====================================================

insert into products
  (id, slug, name, category_slug, reference, short_desc, description, materials, dimensions, hardware, warranty, price_cop, compare_at_cop, stock, featured, is_new, images)
overriding system value
values
  (40, 'perchero-oso-acostado', 'Perchero Oso Acostado', 'mascotas', 'PMS2', 'Oso pardo recostado frente a la montaña.', 'Perchero decorativo con un oso pardo recostado frente a un paisaje de montaña. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 19,5 x 8,5 x 1,5 cms', '1 gancho duplex vertical + 1 sencillo', '6 meses', 12000, 20000, 1, false, true, '[{"url":"/img/products/perchero-oso-acostado.webp","alt":"Perchero Oso Acostado"},{"url":"/img/products/perchero-oso-acostado-2.webp","alt":"Perchero Oso Acostado — vista 2"},{"url":"/img/products/perchero-oso-acostado-3.webp","alt":"Perchero Oso Acostado — vista 3"}]'::jsonb),
  (41, 'perchero-aguila', 'Perchero Águila', 'mascotas', 'PMS3', 'Águila americana en pleno vuelo.', 'Perchero decorativo con un águila americana en pleno vuelo. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 19,5 x 8,5 x 1,5 cms', '1 gancho duplex vertical + 1 sencillo', '6 meses', 12000, 20000, 1, false, true, '[{"url":"/img/products/perchero-aguila.webp","alt":"Perchero Águila"},{"url":"/img/products/perchero-aguila-2.webp","alt":"Perchero Águila — vista 2"},{"url":"/img/products/perchero-aguila-3.webp","alt":"Perchero Águila — vista 3"}]'::jsonb),
  (42, 'perchero-siluetas-mascota-duena', 'Perchero Siluetas Mascota y Dueña', 'mascotas', 'PMS4', 'Siluetas de mascota y dueña al atardecer.', 'Perchero decorativo con las siluetas de una mascota y su dueña. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 19,5 x 8,5 x 1,5 cms', '1 gancho duplex vertical + 1 sencillo', '6 meses', 12000, 20000, 1, false, true, '[{"url":"/img/products/perchero-siluetas-mascota-duena.webp","alt":"Perchero Siluetas Mascota y Dueña"},{"url":"/img/products/perchero-siluetas-mascota-duena-2.webp","alt":"Perchero Siluetas Mascota y Dueña — vista 2"},{"url":"/img/products/perchero-siluetas-mascota-duena-3.webp","alt":"Perchero Siluetas Mascota y Dueña — vista 3"}]'::jsonb),
  (43, 'perchero-atardecer-playa-mascota-dueno', 'Perchero Atardecer en la Playa Mascota y Dueño', 'mascotas', 'PMS5', 'Mascota y dueño contemplando el atardecer en la playa.', 'Perchero decorativo con la silueta de una mascota y su dueño contemplando el atardecer en la playa. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 19,5 x 8,5 x 1,5 cms', '1 gancho duplex vertical + 1 sencillo', '6 meses', 12000, 20000, 1, false, true, '[{"url":"/img/products/perchero-atardecer-playa-mascota-dueno.webp","alt":"Perchero Atardecer en la Playa Mascota y Dueño"},{"url":"/img/products/perchero-atardecer-playa-mascota-dueno-2.webp","alt":"Perchero Atardecer en la Playa Mascota y Dueño — vista 2"},{"url":"/img/products/perchero-atardecer-playa-mascota-dueno-3.webp","alt":"Perchero Atardecer en la Playa Mascota y Dueño — vista 3"}]'::jsonb),
  (44, 'perchero-cascada-paisaje', 'Perchero Cascada Paisaje', 'mascotas', 'PMS6', 'Cascada gemela en medio del bosque.', 'Perchero decorativo con una cascada gemela en medio del bosque. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 24 x 10 x 1,5 cms', '1 gancho duplex vertical + 1 sencillo', '6 meses', 12000, 20000, 1, false, true, '[{"url":"/img/products/perchero-cascada-paisaje.webp","alt":"Perchero Cascada Paisaje"},{"url":"/img/products/perchero-cascada-paisaje-2.webp","alt":"Perchero Cascada Paisaje — vista 2"},{"url":"/img/products/perchero-cascada-paisaje-3.webp","alt":"Perchero Cascada Paisaje — vista 3"}]'::jsonb),
  (45, 'perchero-labrador-y-gato-cachorros', 'Perchero Labrador y Gato Cachorros', 'mascotas', 'PMS7', 'Cachorro y gatito entre flores rosadas.', 'Perchero decorativo con un cachorro labrador y un gatito entre flores rosadas. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 7,5 x 1,5 cms', '1 gancho duplex vertical + 1 sencillo', '6 meses', 20000, 30000, 1, false, true, '[{"url":"/img/products/perchero-labrador-y-gato-cachorros.webp","alt":"Perchero Labrador y Gato Cachorros"},{"url":"/img/products/perchero-labrador-y-gato-cachorros-2.webp","alt":"Perchero Labrador y Gato Cachorros — vista 2"},{"url":"/img/products/perchero-labrador-y-gato-cachorros-3.webp","alt":"Perchero Labrador y Gato Cachorros — vista 3"}]'::jsonb),
  (46, 'perchero-lobos-aullando', 'Perchero Lobos Aullando', 'mascotas', 'PMS8', 'Lobo aullando bajo la luna llena.', 'Perchero decorativo con un lobo aullando bajo la luna llena. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 29,5 x 8 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 25000, 35000, 1, false, true, '[{"url":"/img/products/perchero-lobos-aullando.webp","alt":"Perchero Lobos Aullando"},{"url":"/img/products/perchero-lobos-aullando-2.webp","alt":"Perchero Lobos Aullando — vista 2"},{"url":"/img/products/perchero-lobos-aullando-3.webp","alt":"Perchero Lobos Aullando — vista 3"}]'::jsonb),
  (47, 'perchero-atardecer-canoa', 'Perchero Atardecer en Canoa', 'hogar', 'PH14', 'Canoa deslizándose bajo el atardecer.', 'Perchero decorativo con una canoa deslizándose sobre el agua bajo un atardecer. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 37,5 x 6 x 1,2 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 30000, 40000, 1, false, true, '[{"url":"/img/products/perchero-atardecer-canoa.webp","alt":"Perchero Atardecer en Canoa"},{"url":"/img/products/perchero-atardecer-canoa-2.webp","alt":"Perchero Atardecer en Canoa — vista 2"},{"url":"/img/products/perchero-atardecer-canoa-3.webp","alt":"Perchero Atardecer en Canoa — vista 3"}]'::jsonb),
  (48, 'perchero-puente-madera-pantano', 'Perchero Puente de Madera en el Pantano', 'hogar', 'PH15', 'Puente de madera atravesando un pantano.', 'Perchero decorativo con un puente de madera atravesando un pantano. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 37,5 x 6 x 1,2 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 30000, 40000, 1, false, true, '[{"url":"/img/products/perchero-puente-madera-pantano.webp","alt":"Perchero Puente de Madera en el Pantano"},{"url":"/img/products/perchero-puente-madera-pantano-2.webp","alt":"Perchero Puente de Madera en el Pantano — vista 2"},{"url":"/img/products/perchero-puente-madera-pantano-3.webp","alt":"Perchero Puente de Madera en el Pantano — vista 3"}]'::jsonb),
  (49, 'perchero-atardecer-rojizo', 'Perchero Atardecer Rojizo', 'hogar', 'PH16', 'Paisaje en tonos rojizos de atardecer.', 'Perchero decorativo con un paisaje en tonos rojizos de atardecer. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 37,5 x 14 x 1,2 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 35000, 45000, 1, false, true, '[{"url":"/img/products/perchero-atardecer-rojizo.webp","alt":"Perchero Atardecer Rojizo"},{"url":"/img/products/perchero-atardecer-rojizo-2.webp","alt":"Perchero Atardecer Rojizo — vista 2"},{"url":"/img/products/perchero-atardecer-rojizo-3.webp","alt":"Perchero Atardecer Rojizo — vista 3"}]'::jsonb),
  (50, 'perchero-casa-en-el-bosque', 'Perchero Casa en el Bosque', 'hogar', 'PH18', 'Cabaña rústica entre árboles de otoño.', 'Perchero decorativo con una cabaña rústica entre árboles de otoño. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 23 x 10 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 15000, 20000, 1, false, true, '[{"url":"/img/products/perchero-casa-en-el-bosque.webp","alt":"Perchero Casa en el Bosque"},{"url":"/img/products/perchero-casa-en-el-bosque-2.webp","alt":"Perchero Casa en el Bosque — vista 2"},{"url":"/img/products/perchero-casa-en-el-bosque-3.webp","alt":"Perchero Casa en el Bosque — vista 3"}]'::jsonb),
  (51, 'perchero-camino-madera-bosque', 'Perchero Camino de Madera en el Bosque', 'hogar', 'PH19', 'Pasarela de madera entre hojas de otoño.', 'Perchero decorativo con una pasarela de madera entre hojas de otoño. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 23 x 10 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 15000, 20000, 1, false, true, '[{"url":"/img/products/perchero-camino-madera-bosque.webp","alt":"Perchero Camino de Madera en el Bosque"},{"url":"/img/products/perchero-camino-madera-bosque-2.webp","alt":"Perchero Camino de Madera en el Bosque — vista 2"},{"url":"/img/products/perchero-camino-madera-bosque-3.webp","alt":"Perchero Camino de Madera en el Bosque — vista 3"}]'::jsonb),
  (52, 'perchero-cerca-blanca-bosque', 'Perchero Cerca Blanca en el Bosque', 'hogar', 'PH20', 'Cerca blanca entre árboles de otoño.', 'Perchero decorativo con una cerca blanca entre árboles de otoño. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 23 x 10 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 15000, 20000, 1, false, true, '[{"url":"/img/products/perchero-cerca-blanca-bosque.webp","alt":"Perchero Cerca Blanca en el Bosque"},{"url":"/img/products/perchero-cerca-blanca-bosque-2.webp","alt":"Perchero Cerca Blanca en el Bosque — vista 2"},{"url":"/img/products/perchero-cerca-blanca-bosque-3.webp","alt":"Perchero Cerca Blanca en el Bosque — vista 3"}]'::jsonb),
  (53, 'perchero-harley-davidson-desierto', 'Perchero Harley Davidson Desierto', 'moteros', 'PMTH1', 'Harley Davidson chopper en el desierto.', 'Perchero organizador de casco y chaqueta con una Harley Davidson chopper en el desierto. Diseño en impresión fotográfica full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 76 x 11 x 1,5 cms', '2 soportes rígidos para casco', '6 meses', 70000, 80000, 1, false, true, '[{"url":"/img/products/perchero-harley-davidson-desierto.webp","alt":"Perchero Harley Davidson Desierto"},{"url":"/img/products/perchero-harley-davidson-desierto-2.webp","alt":"Perchero Harley Davidson Desierto — vista 2"},{"url":"/img/products/perchero-harley-davidson-desierto-3.webp","alt":"Perchero Harley Davidson Desierto — vista 3"},{"url":"/img/products/perchero-harley-davidson-desierto-4.webp","alt":"Perchero Harley Davidson Desierto — vista 4"},{"url":"/img/products/perchero-harley-davidson-desierto-5.webp","alt":"Perchero Harley Davidson Desierto — vista 5"}]'::jsonb),
  (54, 'perchero-ciudad-paisaje-abstracto', 'Perchero Ciudad Paisaje Abstracto', 'moteros', 'PMTH2', 'Skyline urbano en estilo abstracto.', 'Perchero organizador de casco y chaqueta con un skyline urbano en estilo abstracto. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 73 x 10 x 1,5 cms', '2 soportes rígidos para casco', '6 meses', 70000, 80000, 1, false, true, '[{"url":"/img/products/perchero-ciudad-paisaje-abstracto.webp","alt":"Perchero Ciudad Paisaje Abstracto"},{"url":"/img/products/perchero-ciudad-paisaje-abstracto-2.webp","alt":"Perchero Ciudad Paisaje Abstracto — vista 2"},{"url":"/img/products/perchero-ciudad-paisaje-abstracto-3.webp","alt":"Perchero Ciudad Paisaje Abstracto — vista 3"},{"url":"/img/products/perchero-ciudad-paisaje-abstracto-4.webp","alt":"Perchero Ciudad Paisaje Abstracto — vista 4"},{"url":"/img/products/perchero-ciudad-paisaje-abstracto-5.webp","alt":"Perchero Ciudad Paisaje Abstracto — vista 5"}]'::jsonb),
  (55, 'perchero-moto-paisaje-carretera', 'Perchero Moto Paisaje Carretera', 'moteros', 'PMTH4', 'Motocicleta en la carretera abierta.', 'Perchero organizador de casco y chaqueta con una motocicleta en plena carretera abierta. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 70 x 12 x 1,5 cms', '2 soportes rígidos para casco', '6 meses', 55000, 70000, 1, false, true, '[{"url":"/img/products/perchero-moto-paisaje-carretera.webp","alt":"Perchero Moto Paisaje Carretera"},{"url":"/img/products/perchero-moto-paisaje-carretera-2.webp","alt":"Perchero Moto Paisaje Carretera — vista 2"},{"url":"/img/products/perchero-moto-paisaje-carretera-3.webp","alt":"Perchero Moto Paisaje Carretera — vista 3"},{"url":"/img/products/perchero-moto-paisaje-carretera-4.webp","alt":"Perchero Moto Paisaje Carretera — vista 4"},{"url":"/img/products/perchero-moto-paisaje-carretera-5.webp","alt":"Perchero Moto Paisaje Carretera — vista 5"}]'::jsonb),
  (56, 'perchero-ghost-rider', 'Perchero Ghost Rider', 'moteros', 'PMTH5', 'El Motorista Fantasma envuelto en llamas.', 'Perchero organizador de casco y chaqueta con el Motorista Fantasma (Ghost Rider) envuelto en llamas. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 37,5 x 10 x 1,5 cms', '1 soporte rígido para casco + 2 ganchos sencillos', '6 meses', 45000, 60000, 1, false, true, '[{"url":"/img/products/perchero-ghost-rider.webp","alt":"Perchero Ghost Rider"},{"url":"/img/products/perchero-ghost-rider-2.webp","alt":"Perchero Ghost Rider — vista 2"},{"url":"/img/products/perchero-ghost-rider-3.webp","alt":"Perchero Ghost Rider — vista 3"}]'::jsonb),
  (57, 'perchero-harley-davidson-paisaje', 'Perchero Harley Davidson Paisaje', 'moteros', 'PMTH6', 'Harley Davidson entre montañas y desierto.', 'Perchero organizador de casco y chaqueta con una Harley Davidson entre montañas y desierto. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 37,5 x 10 x 1,5 cms', '1 soporte rígido para casco + 1 gancho duplex vertical', '6 meses', 45000, 60000, 1, false, true, '[{"url":"/img/products/perchero-harley-davidson-paisaje.webp","alt":"Perchero Harley Davidson Paisaje"},{"url":"/img/products/perchero-harley-davidson-paisaje-2.webp","alt":"Perchero Harley Davidson Paisaje — vista 2"},{"url":"/img/products/perchero-harley-davidson-paisaje-3.webp","alt":"Perchero Harley Davidson Paisaje — vista 3"}]'::jsonb),
  (58, 'perchero-ciclistas-atardecer', 'Perchero Ciclistas al Atardecer', 'bike', 'PB1', 'Dos ciclistas rodando bajo el atardecer.', 'Perchero decorativo con las siluetas de dos ciclistas rodando bajo el atardecer. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 37,5 x 7 x 1,5 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 25000, 35000, 1, false, true, '[{"url":"/img/products/perchero-ciclistas-atardecer.webp","alt":"Perchero Ciclistas al Atardecer"},{"url":"/img/products/perchero-ciclistas-atardecer-2.webp","alt":"Perchero Ciclistas al Atardecer — vista 2"},{"url":"/img/products/perchero-ciclistas-atardecer-3.webp","alt":"Perchero Ciclistas al Atardecer — vista 3"}]'::jsonb),
  (59, 'cruz-corona-de-espinas', 'Cruz Decorativa Corona de Espinas', 'variados', 'PVCR3', 'Cristo grabado en madera con corona de espinas.', 'Cruz decorativa de pared con la figura de Cristo grabada en madera y corona de espinas. Pieza artesanal en corte láser.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 29 x 21 x 4,5 x 0,5 cms', 'Herraje tipo serrucho (colgante oculto)', '6 meses', 15000, 25000, 1, false, true, '[{"url":"/img/products/cruz-corona-de-espinas.webp","alt":"Cruz Decorativa Corona de Espinas"},{"url":"/img/products/cruz-corona-de-espinas-2.webp","alt":"Cruz Decorativa Corona de Espinas — vista 2"},{"url":"/img/products/cruz-corona-de-espinas-3.webp","alt":"Cruz Decorativa Corona de Espinas — vista 3"}]'::jsonb),
  (60, 'cruz-corona-de-espinas-2', 'Cruz Decorativa Corona de Espinas II', 'variados', 'PVCR4', 'Cristo grabado en madera con corona de espinas.', 'Cruz decorativa de pared con la figura de Cristo grabada en madera y corona de espinas. Pieza artesanal en corte láser.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 29 x 21 x 4,5 x 0,5 cms', 'Herraje tipo serrucho (colgante oculto)', '6 meses', 15000, 25000, 1, false, true, '[{"url":"/img/products/cruz-corona-de-espinas-2.webp","alt":"Cruz Decorativa Corona de Espinas II"},{"url":"/img/products/cruz-corona-de-espinas-2-2.webp","alt":"Cruz Decorativa Corona de Espinas II — vista 2"},{"url":"/img/products/cruz-corona-de-espinas-2-3.webp","alt":"Cruz Decorativa Corona de Espinas II — vista 3"}]'::jsonb),
  (61, 'cruz-rostro-jesus-base', 'Cruz Decorativa Rostro de Jesús con Base', 'variados', 'PVCR5', 'Rostro de Jesús con corona de espinas, con base.', 'Cruz decorativa con el rostro de Jesús y corona de espinas grabados en madera, incluye base de pie. Pieza artesanal en corte láser.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 29 x 21 x 4,5 x 0,5 cms', 'Herraje tipo serrucho (colgante oculto)', '6 meses', 18000, 28000, 1, false, true, '[{"url":"/img/products/cruz-rostro-jesus-base.webp","alt":"Cruz Decorativa Rostro de Jesús con Base"},{"url":"/img/products/cruz-rostro-jesus-base-2.webp","alt":"Cruz Decorativa Rostro de Jesús con Base — vista 2"},{"url":"/img/products/cruz-rostro-jesus-base-3.webp","alt":"Cruz Decorativa Rostro de Jesús con Base — vista 3"}]'::jsonb),
  (62, 'cruz-calvario-base', 'Cruz Decorativa Calvario con Base', 'variados', 'PVCR6', 'Escena de la resurrección, con base.', 'Cruz decorativa con la escena de la resurrección grabada en madera, incluye base de pie. Pieza artesanal en corte láser.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 29 x 21 x 4,5 x 0,5 cms', 'Herraje tipo serrucho (colgante oculto)', '6 meses', 18000, 28000, 1, false, true, '[{"url":"/img/products/cruz-calvario-base.webp","alt":"Cruz Decorativa Calvario con Base"},{"url":"/img/products/cruz-calvario-base-2.webp","alt":"Cruz Decorativa Calvario con Base — vista 2"},{"url":"/img/products/cruz-calvario-base-3.webp","alt":"Cruz Decorativa Calvario con Base — vista 3"},{"url":"/img/products/cruz-calvario-base-4.webp","alt":"Cruz Decorativa Calvario con Base — vista 4"}]'::jsonb)
on conflict (id) do nothing;

-- Reclasifica las cruces CR1/CR2 a "variados" (el Excel actualizado las
-- renombra PVCR1/PVCR2 y las agrupa junto con las cruces nuevas PVCR3-6).
update products set category_slug = 'variados', reference = 'PVCR1' where id = 14;
update products set category_slug = 'variados', reference = 'PVCR2' where id = 15;

-- Amplía fotos de PMS1 (Perchero Huellas Clásico): de 1 a 3.
update products set images = '[{"url":"/img/products/perchero-huellas-clasico.webp","alt":"Perchero Huellas Clásico"},{"url":"/img/products/perchero-huellas-clasico-2.webp","alt":"Perchero Huellas Clásico — vista 2"},{"url":"/img/products/perchero-huellas-clasico-3.webp","alt":"Perchero Huellas Clásico — vista 3"}]'::jsonb where id = 30;

-- Deja la secuencia lista para el próximo producto creado desde /admin.
select setval(
  pg_get_serial_sequence('products', 'id'),
  (select coalesce(max(id), 1) from products)
);
