-- =====================================================
-- Percheros Decorativos — Migración de catálogo a Supabase
-- Ejecutar en: Supabase Dashboard → SQL Editor (una sola vez)
--
-- Antes de correr esto, crea el bucket de Storage para fotos nuevas:
--   Storage → New bucket → nombre "product-images" → Public bucket: ON
-- No hace falta política adicional: las escrituras solo las hace el
-- servidor con la service_role key (supabaseAdmin), igual que "orders".
-- =====================================================

create table if not exists products (
  id             bigint generated always as identity primary key,
  slug           text unique not null,
  name           text not null,
  category_slug  text not null,
  reference      text,
  short_desc     text,
  description    text,
  materials      text,
  dimensions     text,
  hardware       text,
  warranty       text default '6 meses',
  price_cop      numeric(12,2) not null,
  compare_at_cop numeric(12,2),
  stock          integer not null default 0,
  featured       boolean default false,
  is_new         boolean default false,
  images         jsonb not null default '[]',
  created_at     timestamptz default now(),
  updated_at     timestamptz default now()
);

create index if not exists idx_products_category on products(category_slug);
create index if not exists idx_products_slug on products(slug);

create or replace trigger products_updated_at
  before update on products
  for each row execute function set_updated_at();

-- Catálogo actual (39 productos), con id explícito para no romper
-- referencias existentes de carrito/órdenes.
insert into products
  (id, slug, name, category_slug, reference, short_desc, description, materials, dimensions, hardware, warranty, price_cop, compare_at_cop, stock, featured, is_new, images)
values
  (1, 'perchero-la-candelaria-bogota', 'Perchero La Candelaria Bogotá', 'hogar', 'PH1', 'Calles coloniales de La Candelaria, Bogotá.', 'Perchero decorativo con imagen de las calles coloniales de La Candelaria, en el centro histórico de Bogotá. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 7,5 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 30000, 40000, 2, true, false, '[{"url":"/img/products/perchero-la-candelaria-bogota.webp","alt":"Perchero La Candelaria Bogotá"},{"url":"/img/products/perchero-la-candelaria-bogota-2.webp","alt":"Perchero La Candelaria Bogotá — vista 2"},{"url":"/img/products/perchero-la-candelaria-bogota-3.webp","alt":"Perchero La Candelaria Bogotá — vista 3"}]'::jsonb),
  (2, 'perchero-la-candelaria-colores', 'Perchero La Candelaria Casas de Colores', 'hogar', 'PH1-1', 'Fachadas coloridas del barrio La Candelaria.', 'Perchero decorativo con las fachadas coloridas del barrio La Candelaria de Bogotá. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 7,5 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 30000, 40000, 2, false, false, '[{"url":"/img/products/perchero-la-candelaria-colores.webp","alt":"Perchero La Candelaria Casas de Colores"},{"url":"/img/products/perchero-la-candelaria-colores-2.webp","alt":"Perchero La Candelaria Casas de Colores — vista 2"},{"url":"/img/products/perchero-la-candelaria-colores-3.webp","alt":"Perchero La Candelaria Casas de Colores — vista 3"}]'::jsonb),
  (3, 'perchero-monserrate-bogota', 'Perchero Monserrate Bogotá', 'hogar', 'PH2', 'El santuario de Monserrate sobre Bogotá.', 'Perchero decorativo con vista panorámica del santuario de Monserrate y la ciudad de Bogotá. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 29,5 x 8 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 25000, 35000, 2, true, false, '[{"url":"/img/products/perchero-monserrate-bogota.webp","alt":"Perchero Monserrate Bogotá"},{"url":"/img/products/perchero-monserrate-bogota-2.webp","alt":"Perchero Monserrate Bogotá — vista 2"},{"url":"/img/products/perchero-monserrate-bogota-3.webp","alt":"Perchero Monserrate Bogotá — vista 3"}]'::jsonb),
  (4, 'perchero-mandalas', 'Perchero Mandalas', 'hogar', 'PH3', 'Mandalas multicolores llenos de energía.', 'Perchero decorativo con mandalas multicolores, ideal para dar vida y energía a cualquier espacio. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 7,5 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 25000, 35000, 2, false, false, '[{"url":"/img/products/perchero-mandalas.webp","alt":"Perchero Mandalas"},{"url":"/img/products/perchero-mandalas-2.webp","alt":"Perchero Mandalas — vista 2"},{"url":"/img/products/perchero-mandalas-3.webp","alt":"Perchero Mandalas — vista 3"}]'::jsonb),
  (5, 'perchero-plaza-de-bolivar', 'Perchero Plaza de Bolívar Bogotá', 'hogar', 'PH4', 'La Catedral y la Plaza de Bolívar de Bogotá.', 'Perchero decorativo con la Plaza de Bolívar y la Catedral Primada de Bogotá. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 7,5 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 25000, NULL, 1, true, false, '[{"url":"/img/products/perchero-plaza-de-bolivar.webp","alt":"Perchero Plaza de Bolívar Bogotá"},{"url":"/img/products/perchero-plaza-de-bolivar-2.webp","alt":"Perchero Plaza de Bolívar Bogotá — vista 2"},{"url":"/img/products/perchero-plaza-de-bolivar-3.webp","alt":"Perchero Plaza de Bolívar Bogotá — vista 3"}]'::jsonb),
  (6, 'perchero-muelle-paisaje-azul', 'Perchero Muelle Paisaje Azul', 'hogar', 'PH5', 'Muelle nocturno en tonos azules.', 'Perchero decorativo con un muelle en tonos azules. Diseño tallado directamente en madera, pieza única artesanal.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 37,5 x 6 x 1,2 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 30000, 40000, 1, true, false, '[{"url":"/img/products/perchero-muelle-paisaje-azul.webp","alt":"Perchero Muelle Paisaje Azul"},{"url":"/img/products/perchero-muelle-paisaje-azul-2.webp","alt":"Perchero Muelle Paisaje Azul — vista 2"},{"url":"/img/products/perchero-muelle-paisaje-azul-3.webp","alt":"Perchero Muelle Paisaje Azul — vista 3"}]'::jsonb),
  (7, 'perchero-atardecer-en-bici', 'Perchero Atardecer en Bici', 'hogar', 'PH6', 'Siluetas de ciclistas al caer el sol.', 'Perchero decorativo con siluetas de ciclistas al atardecer, perfecto para los amantes de la bici. Diseño tallado directamente en madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 37,5 x 6 x 1,2 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 30000, 40000, 1, false, false, '[{"url":"/img/products/perchero-atardecer-en-bici.webp","alt":"Perchero Atardecer en Bici"},{"url":"/img/products/perchero-atardecer-en-bici-2.webp","alt":"Perchero Atardecer en Bici — vista 2"},{"url":"/img/products/perchero-atardecer-en-bici-3.webp","alt":"Perchero Atardecer en Bici — vista 3"}]'::jsonb),
  (8, 'perchero-bosque', 'Perchero Bosque', 'hogar', 'PH7', 'Bosque en tonos dorados y luz cálida.', 'Perchero decorativo con un bosque en luz cálida, naturaleza para tu hogar. Diseño tallado directamente en madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 37,5 x 6 x 1,2 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 30000, 40000, 1, false, false, '[{"url":"/img/products/perchero-bosque.webp","alt":"Perchero Bosque"},{"url":"/img/products/perchero-bosque-2.webp","alt":"Perchero Bosque — vista 2"},{"url":"/img/products/perchero-bosque-3.webp","alt":"Perchero Bosque — vista 3"}]'::jsonb),
  (9, 'perchero-ciudad-y-golfo', 'Perchero Paisaje Ciudad y Golfo', 'hogar', 'PH8', 'Skyline urbano junto al golfo.', 'Perchero decorativo con el skyline de la ciudad junto al golfo. Estilo urbano para colgar llaves, gorras y accesorios. Diseño tallado directamente en madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 37,5 x 6 x 1,2 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 30000, 40000, 1, false, false, '[{"url":"/img/products/perchero-ciudad-y-golfo.webp","alt":"Perchero Paisaje Ciudad y Golfo"},{"url":"/img/products/perchero-ciudad-y-golfo-2.webp","alt":"Perchero Paisaje Ciudad y Golfo — vista 2"},{"url":"/img/products/perchero-ciudad-y-golfo-3.webp","alt":"Perchero Paisaje Ciudad y Golfo — vista 3"}]'::jsonb),
  (10, 'perchero-tren-epoca-de-nieve', 'Perchero Tren en Época de Nieve', 'hogar', 'PH9', 'Locomotora clásica entre paisaje nevado.', 'Perchero decorativo con una locomotora clásica atravesando un paisaje nevado. Diseño tallado directamente en madera, encanto vintage.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 37,5 x 6 x 1,2 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 30000, 40000, 1, false, false, '[{"url":"/img/products/perchero-tren-epoca-de-nieve.webp","alt":"Perchero Tren en Época de Nieve"},{"url":"/img/products/perchero-tren-epoca-de-nieve-2.webp","alt":"Perchero Tren en Época de Nieve — vista 2"},{"url":"/img/products/perchero-tren-epoca-de-nieve-3.webp","alt":"Perchero Tren en Época de Nieve — vista 3"}]'::jsonb),
  (11, 'perchero-torre-colpatria', 'Perchero Torre Colpatria Bogotá', 'hogar', 'PH10', 'Atardecer bogotano con la Torre Colpatria.', 'Perchero decorativo con el atardecer de Bogotá y la Torre Colpatria como protagonista. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 8 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 25000, 35000, 1, true, false, '[{"url":"/img/products/perchero-torre-colpatria.webp","alt":"Perchero Torre Colpatria Bogotá"},{"url":"/img/products/perchero-torre-colpatria-2.webp","alt":"Perchero Torre Colpatria Bogotá — vista 2"},{"url":"/img/products/perchero-torre-colpatria-3.webp","alt":"Perchero Torre Colpatria Bogotá — vista 3"}]'::jsonb),
  (12, 'perchero-puente-manhattan', 'Perchero Puente de Manhattan', 'hogar', 'PH11', 'El icónico puente entre edificios de ladrillo.', 'Perchero decorativo con el icónico puente de Manhattan. Diseño combinando impresión full color y talla en madera, estilo neoyorquino.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 8 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 25000, 35000, 1, false, false, '[{"url":"/img/products/perchero-puente-manhattan.webp","alt":"Perchero Puente de Manhattan"},{"url":"/img/products/perchero-puente-manhattan-2.webp","alt":"Perchero Puente de Manhattan — vista 2"},{"url":"/img/products/perchero-puente-manhattan-3.webp","alt":"Perchero Puente de Manhattan — vista 3"}]'::jsonb),
  (13, 'perchero-bahia-skyline', 'Perchero Bahía Skyline', 'hogar', 'PH17', 'Panorámica de ciudad y bahía, 4 herrajes.', 'Perchero decorativo panorámico con vista de la ciudad y su bahía. Con cuatro herrajes, ideal para familias y entradas con mucho movimiento. Diseño combinando impresión full color y talla en madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 62 x 8 x 1,5 cms', '4 ganchos duplex verticales', '6 meses', 45000, 55000, 1, false, false, '[{"url":"/img/products/perchero-bahia-skyline.webp","alt":"Perchero Bahía Skyline"},{"url":"/img/products/perchero-bahia-skyline-2.webp","alt":"Perchero Bahía Skyline — vista 2"},{"url":"/img/products/perchero-bahia-skyline-3.webp","alt":"Perchero Bahía Skyline — vista 3"}]'::jsonb),
  (14, 'cruz-manos-en-oracion', 'Cruz Decorativa Manos en Oración', 'dedios', 'CR1', 'Cruz de pared con manos en oración.', 'Cruz decorativa de pared con imagen de manos en oración y cruz al atardecer. Diseño en impresión de vinilo full color sobre madera. Una pieza de fe para acompañar tu hogar.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 45 x 32 x 1,5 cms', 'Herraje tipo serrucho (colgante oculto)', '6 meses', 55000, 65000, 1, false, false, '[{"url":"/img/products/cruz-manos-en-oracion.webp","alt":"Cruz Decorativa Manos en Oración"},{"url":"/img/products/cruz-manos-en-oracion-2.webp","alt":"Cruz Decorativa Manos en Oración — vista 2"}]'::jsonb),
  (15, 'cruz-amanecer', 'Cruz Decorativa Cruz del Monte', 'dedios', 'CR2', 'Cruz de pared con amanecer en el calvario.', 'Cruz decorativa de pared con la imagen de la cruz del calvario al amanecer. Diseño en impresión de vinilo full color sobre madera. Fe y esperanza para tu hogar.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 45 x 32 x 1,5 cms', 'Herraje tipo serrucho (colgante oculto)', '6 meses', 65000, 75000, 1, false, false, '[{"url":"/img/products/cruz-amanecer.webp","alt":"Cruz Decorativa Cruz del Monte"},{"url":"/img/products/cruz-amanecer-2.webp","alt":"Cruz Decorativa Cruz del Monte — vista 2"},{"url":"/img/products/cruz-amanecer-3.webp","alt":"Cruz Decorativa Cruz del Monte — vista 3"}]'::jsonb),
  (16, 'perchero-ultima-cena', 'Perchero Última Cena', 'dedios', 'PdD1', 'La Última Cena tallada en madera.', 'Perchero decorativo con la imagen de la Última Cena. Diseño tallado directamente en madera. Una pieza clásica de fe para el comedor o la entrada del hogar.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 34 x 7 x 2 cms', '2 ganchos duplex verticales', '6 meses', 25000, 35000, 2, true, false, '[{"url":"/img/products/perchero-ultima-cena.webp","alt":"Perchero Última Cena"},{"url":"/img/products/perchero-ultima-cena-2.webp","alt":"Perchero Última Cena — vista 2"},{"url":"/img/products/perchero-ultima-cena-3.webp","alt":"Perchero Última Cena — vista 3"}]'::jsonb),
  (17, 'perchero-espiritu-santo', 'Perchero Espíritu Santo', 'dedios', 'PdD2', 'La paloma del Espíritu Santo entre nubes.', 'Perchero decorativo con la paloma del Espíritu Santo entre nubes. Diseño tallado directamente en madera. Paz y organización para tu hogar.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 7,5 x 1,5 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 30000, 40000, 2, true, false, '[{"url":"/img/products/perchero-espiritu-santo.webp","alt":"Perchero Espíritu Santo"},{"url":"/img/products/perchero-espiritu-santo-2.webp","alt":"Perchero Espíritu Santo — vista 2"}]'::jsonb),
  (18, 'perchero-biblia-luz', 'Perchero La Biblia', 'dedios', 'PdD3', 'Biblia abierta iluminada por luz divina.', 'Perchero decorativo con una Biblia abierta iluminada por un rayo de luz. Diseño en impresión de vinilo full color sobre madera. La Palabra siempre presente en tu hogar.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 7,5 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 25000, 35000, 1, false, false, '[{"url":"/img/products/perchero-biblia-luz.webp","alt":"Perchero La Biblia"},{"url":"/img/products/perchero-biblia-luz-2.webp","alt":"Perchero La Biblia — vista 2"},{"url":"/img/products/perchero-biblia-luz-3.webp","alt":"Perchero La Biblia — vista 3"}]'::jsonb),
  (19, 'perchero-jesus-viendo-la-ciudad', 'Perchero Jesús Viendo la Ciudad', 'dedios', 'PdD4', 'Jesús sentado, contemplando la ciudad.', 'Perchero decorativo con la imagen de Jesús sentado, viendo la ciudad. Diseño combinando impresión full color y talla en madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 10 x 1,5 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 35000, 45000, 1, false, false, '[{"url":"/img/products/perchero-jesus-viendo-la-ciudad.webp","alt":"Perchero Jesús Viendo la Ciudad"},{"url":"/img/products/perchero-jesus-viendo-la-ciudad-2.webp","alt":"Perchero Jesús Viendo la Ciudad — vista 2"},{"url":"/img/products/perchero-jesus-viendo-la-ciudad-3.webp","alt":"Perchero Jesús Viendo la Ciudad — vista 3"}]'::jsonb),
  (20, 'perchero-cruz-de-rodillas', 'Perchero La Cruz y De Rodillas', 'dedios', 'PdD5', 'La cruz y una figura de rodillas en oración.', 'Perchero decorativo con la cruz y una figura de rodillas en oración. Diseño combinando impresión full color y talla en madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 10 x 1,5 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 35000, 45000, 1, false, false, '[{"url":"/img/products/perchero-cruz-de-rodillas.webp","alt":"Perchero La Cruz y De Rodillas"},{"url":"/img/products/perchero-cruz-de-rodillas-2.webp","alt":"Perchero La Cruz y De Rodillas — vista 2"},{"url":"/img/products/perchero-cruz-de-rodillas-3.webp","alt":"Perchero La Cruz y De Rodillas — vista 3"}]'::jsonb),
  (21, 'perchero-buen-pastor', 'Perchero Jesús Pastor', 'dedios', 'PdD6', 'Jesús el Buen Pastor entre montañas.', 'Perchero decorativo con la imagen de Jesús el Buen Pastor caminando entre montañas. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 7,5 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 25000, 35000, 2, false, false, '[{"url":"/img/products/perchero-buen-pastor.webp","alt":"Perchero Jesús Pastor"},{"url":"/img/products/perchero-buen-pastor-2.webp","alt":"Perchero Jesús Pastor — vista 2"},{"url":"/img/products/perchero-buen-pastor-3.webp","alt":"Perchero Jesús Pastor — vista 3"}]'::jsonb),
  (22, 'perchero-en-tus-manos', 'Perchero Padre en Tus Manos Encomiendo Mi Espíritu', 'dedios', 'PdD7', 'Frase de fe con la imagen de Jesús.', 'Perchero decorativo con la frase “Padre, en tus manos encomiendo mi espíritu” y la imagen de Jesús. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 7,5 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 25000, 35000, 2, false, false, '[{"url":"/img/products/perchero-en-tus-manos.webp","alt":"Perchero Padre en Tus Manos Encomiendo Mi Espíritu"},{"url":"/img/products/perchero-en-tus-manos-2.webp","alt":"Perchero Padre en Tus Manos Encomiendo Mi Espíritu — vista 2"},{"url":"/img/products/perchero-en-tus-manos-3.webp","alt":"Perchero Padre en Tus Manos Encomiendo Mi Espíritu — vista 3"}]'::jsonb),
  (23, 'perchero-mi-fortaleza', 'Perchero Cruz con Rosario — Tú Eres Mi Fortaleza', 'dedios', 'PdD8', 'Cruz con rosario y frase de fortaleza.', 'Perchero decorativo con una cruz, un rosario y la frase “Tú eres mi Fortaleza”. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 8 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 25000, 35000, 1, false, false, '[{"url":"/img/products/perchero-mi-fortaleza.webp","alt":"Perchero Cruz con Rosario — Tú Eres Mi Fortaleza"},{"url":"/img/products/perchero-mi-fortaleza-2.webp","alt":"Perchero Cruz con Rosario — Tú Eres Mi Fortaleza — vista 2"},{"url":"/img/products/perchero-mi-fortaleza-3.webp","alt":"Perchero Cruz con Rosario — Tú Eres Mi Fortaleza — vista 3"}]'::jsonb),
  (24, 'perchero-cruz-al-madero', 'Perchero Cruz al Madero Nuestros Pecados', 'dedios', 'PdD9', 'Cruz al atardecer con versículo bíblico.', 'Perchero decorativo con la cruz al atardecer y el versículo “Él mismo, en su cuerpo, llevó al madero nuestros pecados”. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 8 x 1,5 cms', '2 ganchos duplex verticales', '6 meses', 25000, 35000, 2, true, false, '[{"url":"/img/products/perchero-cruz-al-madero.webp","alt":"Perchero Cruz al Madero Nuestros Pecados"},{"url":"/img/products/perchero-cruz-al-madero-2.webp","alt":"Perchero Cruz al Madero Nuestros Pecados — vista 2"},{"url":"/img/products/perchero-cruz-al-madero-3.webp","alt":"Perchero Cruz al Madero Nuestros Pecados — vista 3"}]'::jsonb),
  (25, 'soporte-guitarra-iron-maiden', 'Soporte de Guitarra Iron Maiden', 'guitarras', 'PG1', 'Soporte de pared con arte de Iron Maiden.', 'Soporte de pared para guitarra con arte inspirado en Iron Maiden. Diseño en impresión de vinilo full color sobre madera. Cuelga tu guitarra como pieza de colección.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 19 x 19 x 1,5 cms', 'Soporte ajustable para guitarra', '6 meses', 45000, 55000, 2, true, false, '[{"url":"/img/products/soporte-guitarra-iron-maiden.webp","alt":"Soporte de Guitarra Iron Maiden"},{"url":"/img/products/soporte-guitarra-iron-maiden-2.webp","alt":"Soporte de Guitarra Iron Maiden — vista 2"},{"url":"/img/products/soporte-guitarra-iron-maiden-3.webp","alt":"Soporte de Guitarra Iron Maiden — vista 3"}]'::jsonb),
  (26, 'soporte-guitarra-heroes-del-silencio', 'Soporte de Guitarra Héroes del Silencio', 'guitarras', 'PG2', 'Soporte de pared con isotipo de Héroes del Silencio.', 'Soporte de pared para guitarra con el isotipo de Héroes del Silencio. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 19 x 19 x 1,5 cms', 'Soporte ajustable para guitarra', '6 meses', 45000, 55000, 2, false, false, '[{"url":"/img/products/soporte-guitarra-heroes-del-silencio.webp","alt":"Soporte de Guitarra Héroes del Silencio"},{"url":"/img/products/soporte-guitarra-heroes-del-silencio-2.webp","alt":"Soporte de Guitarra Héroes del Silencio — vista 2"},{"url":"/img/products/soporte-guitarra-heroes-del-silencio-3.webp","alt":"Soporte de Guitarra Héroes del Silencio — vista 3"}]'::jsonb),
  (27, 'soporte-guitarra-acdc', 'Soporte de Guitarra AC/DC', 'guitarras', 'PG3', 'Soporte de pared con arte de AC/DC.', 'Soporte de pared para guitarra con arte inspirado en AC/DC. Diseño en impresión de vinilo full color sobre madera. Alta tensión para tu espacio musical.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 19 x 19 x 1,5 cms', 'Soporte ajustable para guitarra', '6 meses', 45000, 55000, 1, true, false, '[{"url":"/img/products/soporte-guitarra-acdc.webp","alt":"Soporte de Guitarra AC/DC"},{"url":"/img/products/soporte-guitarra-acdc-2.webp","alt":"Soporte de Guitarra AC/DC — vista 2"},{"url":"/img/products/soporte-guitarra-acdc-3.webp","alt":"Soporte de Guitarra AC/DC — vista 3"}]'::jsonb),
  (28, 'soporte-guitarra-soda-stereo', 'Soporte de Guitarra Soda Stereo', 'guitarras', 'PG4', 'Soporte de pared con arte de Soda Stereo.', 'Soporte de pared para guitarra con arte inspirado en Soda Stereo. Diseño en impresión de vinilo full color sobre madera. Un clásico del rock en español.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 19 x 19 x 1,5 cms', 'Soporte ajustable para guitarra', '6 meses', 45000, 55000, 1, false, false, '[{"url":"/img/products/soporte-guitarra-soda-stereo.webp","alt":"Soporte de Guitarra Soda Stereo"},{"url":"/img/products/soporte-guitarra-soda-stereo-2.webp","alt":"Soporte de Guitarra Soda Stereo — vista 2"}]'::jsonb),
  (29, 'soporte-guitarra-metallica', 'Soporte de Guitarra Metallica', 'guitarras', 'PG6', 'Soporte de pared con arte de Metallica.', 'Soporte de pared para guitarra con arte inspirado en Metallica. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 19 x 19 x 1,5 cms', 'Soporte ajustable para guitarra', '6 meses', 45000, 55000, 1, false, false, '[{"url":"/img/products/soporte-guitarra-metallica.webp","alt":"Soporte de Guitarra Metallica"},{"url":"/img/products/soporte-guitarra-metallica-2.webp","alt":"Soporte de Guitarra Metallica — vista 2"}]'::jsonb),
  (30, 'perchero-huellas-clasico', 'Perchero Huellas Clásico', 'mascotas', 'PMS1', 'Huellas sobre fondo dorado, 3 herrajes.', 'Perchero con diseño de huellas sobre fondo dorado. Diseño en impresión de vinilo full color sobre madera. Organiza correas, arneses y accesorios de tu mascota.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 30 x 7,5 x 1,5 cms', '2 ganchos duplex verticales + 1 sencillo', '6 meses', 30000, 40000, 1, false, false, '[{"url":"/img/products/perchero-huellas-clasico.webp","alt":"Perchero Huellas Clásico"}]'::jsonb),
  (31, 'perchero-guitarra-en-llamas', 'Perchero Guitarra en Llamas', 'moteros', 'PMTV1', 'Organizador de casco con guitarra en llamas.', 'Perchero organizador de casco y chaqueta con una guitarra envuelta en llamas. Diseño tallado directamente en madera. Sostiene el casco con firmeza gracias a sus dos soportes rígidos.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 73 x 10 x 1,5 cms', '2 soportes rígidos para casco', '6 meses', 70000, 80000, 1, true, true, '[{"url":"/img/products/perchero-guitarra-en-llamas.webp","alt":"Perchero Guitarra en Llamas"},{"url":"/img/products/perchero-guitarra-en-llamas-2.webp","alt":"Perchero Guitarra en Llamas — vista 2"},{"url":"/img/products/perchero-guitarra-en-llamas-3.webp","alt":"Perchero Guitarra en Llamas — vista 3"},{"url":"/img/products/perchero-guitarra-en-llamas-4.webp","alt":"Perchero Guitarra en Llamas — vista 4"},{"url":"/img/products/perchero-guitarra-en-llamas-5.webp","alt":"Perchero Guitarra en Llamas — vista 5"}]'::jsonb),
  (32, 'perchero-moto-tren-delantero', 'Perchero Moto Tren Delantero', 'moteros', 'PMTV2', 'Organizador de casco con vista frontal de moto.', 'Perchero organizador de casco y chaqueta con la vista frontal de una motocicleta al atardecer. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 75 x 11 x 1,5 cms', '2 soportes rígidos para casco', '6 meses', 50000, 80000, 1, false, true, '[{"url":"/img/products/perchero-moto-tren-delantero.webp","alt":"Perchero Moto Tren Delantero"},{"url":"/img/products/perchero-moto-tren-delantero-2.webp","alt":"Perchero Moto Tren Delantero — vista 2"},{"url":"/img/products/perchero-moto-tren-delantero-3.webp","alt":"Perchero Moto Tren Delantero — vista 3"},{"url":"/img/products/perchero-moto-tren-delantero-4.webp","alt":"Perchero Moto Tren Delantero — vista 4"},{"url":"/img/products/perchero-moto-tren-delantero-5.webp","alt":"Perchero Moto Tren Delantero — vista 5"}]'::jsonb),
  (33, 'perchero-motero-fondo-amarillo', 'Perchero Motero Fondo Amarillo', 'moteros', 'PMTV3', 'Motero de frente sobre fondo amarillo atardecer.', 'Perchero organizador de casco y chaqueta con un motero de frente sobre un fondo amarillo de atardecer. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 75 x 11 x 1,5 cms', '2 soportes rígidos para casco', '6 meses', 50000, 80000, 1, false, true, '[{"url":"/img/products/perchero-motero-fondo-amarillo.webp","alt":"Perchero Motero Fondo Amarillo"},{"url":"/img/products/perchero-motero-fondo-amarillo-2.webp","alt":"Perchero Motero Fondo Amarillo — vista 2"},{"url":"/img/products/perchero-motero-fondo-amarillo-3.webp","alt":"Perchero Motero Fondo Amarillo — vista 3"},{"url":"/img/products/perchero-motero-fondo-amarillo-4.webp","alt":"Perchero Motero Fondo Amarillo — vista 4"},{"url":"/img/products/perchero-motero-fondo-amarillo-5.webp","alt":"Perchero Motero Fondo Amarillo — vista 5"}]'::jsonb),
  (34, 'perchero-motero-aprilia', 'Perchero Motero Aprilia', 'moteros', 'PMTV4', 'Motero de frente con moto Aprilia.', 'Perchero organizador de casco y chaqueta con un motero de frente sobre una Aprilia. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 73 x 10 x 1,5 cms', '2 soportes rígidos para casco', '6 meses', 60000, 70000, 1, false, true, '[{"url":"/img/products/perchero-motero-aprilia.webp","alt":"Perchero Motero Aprilia"},{"url":"/img/products/perchero-motero-aprilia-2.webp","alt":"Perchero Motero Aprilia — vista 2"},{"url":"/img/products/perchero-motero-aprilia-3.webp","alt":"Perchero Motero Aprilia — vista 3"},{"url":"/img/products/perchero-motero-aprilia-4.webp","alt":"Perchero Motero Aprilia — vista 4"},{"url":"/img/products/perchero-motero-aprilia-5.webp","alt":"Perchero Motero Aprilia — vista 5"}]'::jsonb),
  (35, 'perchero-helicoptero', 'Perchero Helicóptero', 'moteros', 'PMTV5', 'Helicóptero sobrevolando la ciudad al atardecer.', 'Perchero organizador de casco y chaqueta con un helicóptero sobrevolando la ciudad al atardecer. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 73 x 10 x 1,5 cms', '2 soportes rígidos para casco', '6 meses', 70000, 80000, 1, true, true, '[{"url":"/img/products/perchero-helicoptero.webp","alt":"Perchero Helicóptero"},{"url":"/img/products/perchero-helicoptero-2.webp","alt":"Perchero Helicóptero — vista 2"},{"url":"/img/products/perchero-helicoptero-3.webp","alt":"Perchero Helicóptero — vista 3"},{"url":"/img/products/perchero-helicoptero-4.webp","alt":"Perchero Helicóptero — vista 4"},{"url":"/img/products/perchero-helicoptero-5.webp","alt":"Perchero Helicóptero — vista 5"}]'::jsonb),
  (36, 'perchero-escudo-nacional', 'Perchero Escudo Atlético Nacional', 'moteros', 'PMTV6', 'Escudo de Atlético Nacional sobre fondo verde.', 'Perchero organizador de casco y chaqueta con el escudo de Atlético Nacional. Diseño en impresión de vinilo full color sobre madera. Para los hinchas verdolagas.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 73 x 10 x 1,5 cms', '2 soportes rígidos para casco', '6 meses', 60000, 70000, 1, false, true, '[{"url":"/img/products/perchero-escudo-nacional.webp","alt":"Perchero Escudo Atlético Nacional"},{"url":"/img/products/perchero-escudo-nacional-2.webp","alt":"Perchero Escudo Atlético Nacional — vista 2"},{"url":"/img/products/perchero-escudo-nacional-3.webp","alt":"Perchero Escudo Atlético Nacional — vista 3"},{"url":"/img/products/perchero-escudo-nacional-4.webp","alt":"Perchero Escudo Atlético Nacional — vista 4"},{"url":"/img/products/perchero-escudo-nacional-5.webp","alt":"Perchero Escudo Atlético Nacional — vista 5"}]'::jsonb),
  (37, 'perchero-escudo-millonarios', 'Perchero Escudo Millonarios', 'moteros', 'PMTV7', 'Escudo de Millonarios F.C.', 'Perchero organizador de casco y chaqueta con el escudo de Millonarios F.C. Diseño en impresión de vinilo full color sobre madera. Para los hinchas del embajador.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 73 x 10 x 1,5 cms', '2 soportes rígidos para casco', '6 meses', 60000, 70000, 1, false, true, '[{"url":"/img/products/perchero-escudo-millonarios.webp","alt":"Perchero Escudo Millonarios"},{"url":"/img/products/perchero-escudo-millonarios-2.webp","alt":"Perchero Escudo Millonarios — vista 2"},{"url":"/img/products/perchero-escudo-millonarios-3.webp","alt":"Perchero Escudo Millonarios — vista 3"},{"url":"/img/products/perchero-escudo-millonarios-4.webp","alt":"Perchero Escudo Millonarios — vista 4"},{"url":"/img/products/perchero-escudo-millonarios-5.webp","alt":"Perchero Escudo Millonarios — vista 5"}]'::jsonb),
  (38, 'perchero-flores-rosadas', 'Perchero Flores Rosadas', 'moteros', 'PMTV8', 'Mandala floral en tonos rosados.', 'Perchero organizador de casco y chaqueta con un mandala floral en tonos rosados. Diseño en impresión de vinilo full color sobre madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 73 x 8 x 1,5 cms', '2 soportes rígidos para casco', '6 meses', 60000, 70000, 1, false, true, '[{"url":"/img/products/perchero-flores-rosadas.webp","alt":"Perchero Flores Rosadas"},{"url":"/img/products/perchero-flores-rosadas-2.webp","alt":"Perchero Flores Rosadas — vista 2"},{"url":"/img/products/perchero-flores-rosadas-3.webp","alt":"Perchero Flores Rosadas — vista 3"},{"url":"/img/products/perchero-flores-rosadas-4.webp","alt":"Perchero Flores Rosadas — vista 4"},{"url":"/img/products/perchero-flores-rosadas-5.webp","alt":"Perchero Flores Rosadas — vista 5"}]'::jsonb),
  (39, 'perchero-tren-bajo-el-agua', 'Perchero Tren Bajo el Agua', 'moteros', 'PMTV9', 'Locomotora de vapor entre reflejos de agua.', 'Perchero organizador de casco y chaqueta con una locomotora de vapor entre reflejos de agua. Diseño tallado directamente en madera.', 'Fabricados en madera atemporal de re-origen, impresión en vinilo adhesivo full color, herrajes metálicos de diferentes referencias.', 'Aprox. 70 x 12 x 1,5 cms', '2 soportes rígidos para casco', '6 meses', 70000, 80000, 1, false, true, '[{"url":"/img/products/perchero-tren-bajo-el-agua.webp","alt":"Perchero Tren Bajo el Agua"},{"url":"/img/products/perchero-tren-bajo-el-agua-2.webp","alt":"Perchero Tren Bajo el Agua — vista 2"},{"url":"/img/products/perchero-tren-bajo-el-agua-3.webp","alt":"Perchero Tren Bajo el Agua — vista 3"},{"url":"/img/products/perchero-tren-bajo-el-agua-4.webp","alt":"Perchero Tren Bajo el Agua — vista 4"},{"url":"/img/products/perchero-tren-bajo-el-agua-5.webp","alt":"Perchero Tren Bajo el Agua — vista 5"}]'::jsonb)
on conflict (id) do nothing;

-- Deja la secuencia lista para que el próximo producto creado desde el
-- panel siga en 40 en vez de chocar con estos ids explícitos.
select setval(
  pg_get_serial_sequence('products', 'id'),
  (select coalesce(max(id), 1) from products)
);
